/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminNotificationEnable {
    'create'?: boolean;
    'modify'?: boolean;
    'delete'?: boolean;
    'reset_usage'?: boolean;
    'login'?: boolean;
    'usage_limit_warning'?: boolean;
    'usage_limit_warning_percentages'?: Array<number>;
}

