/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RoleLimits } from './role-limits';
// May contain unused imports in some cases
// @ts-ignore
import type { UserNotificationEnable } from './user-notification-enable';

/**
 * Model for creating new admin accounts requiring username and password.
 * @export
 * @interface AdminCreate
 */
export interface AdminCreate {
    /**
     * 
     * @type {string}
     * @memberof AdminCreate
     */
    'password': string;
    /**
     * 
     * @type {number}
     * @memberof AdminCreate
     */
    'telegram_id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AdminCreate
     */
    'discord_webhook'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminCreate
     */
    'status'?: AdminCreateStatusEnum | null;
    /**
     * 
     * @type {number}
     * @memberof AdminCreate
     */
    'data_limit'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AdminCreate
     */
    'sub_template'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminCreate
     */
    'sub_domain'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminCreate
     */
    'profile_title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminCreate
     */
    'support_url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminCreate
     */
    'note'?: string | null;
    /**
     * 
     * @type {UserNotificationEnable}
     * @memberof AdminCreate
     */
    'notification_enable'?: UserNotificationEnable | null;
    /**
     * 
     * @type {number}
     * @memberof AdminCreate
     */
    'role_id': number;
    /**
     * 
     * @type {RoleLimits}
     * @memberof AdminCreate
     */
    'permission_overrides'?: RoleLimits | null;
    /**
     * 
     * @type {string}
     * @memberof AdminCreate
     */
    'username': string;
}

export const AdminCreateStatusEnum = {
    Active: 'active',
    Disabled: 'disabled'
} as const;

export type AdminCreateStatusEnum = typeof AdminCreateStatusEnum[keyof typeof AdminCreateStatusEnum];


