/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 4.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AdminSimple } from './admin-simple';

/**
 * Response model for lightweight admin list.
 * @export
 * @interface AdminsSimpleResponse
 */
export interface AdminsSimpleResponse {
    /**
     * 
     * @type {Array<AdminSimple>}
     * @memberof AdminsSimpleResponse
     */
    'admins': Array<AdminSimple>;
    /**
     * 
     * @type {number}
     * @memberof AdminsSimpleResponse
     */
    'total': number;
}

