/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CustomVariable } from './custom-variable';
// May contain unused imports in some cases
// @ts-ignore
import type { UserNotificationEnable } from './user-notification-enable';

/**
 * Base model containing the core admin identification fields.
 */
export interface AdminContactInfo {
    'id'?: number | null;
    'username': string;
    'telegram_id'?: number | null;
    'discord_webhook'?: string | null;
    'sub_domain'?: string | null;
    'profile_title'?: string | null;
    'support_url'?: string | null;
    'custom_variables'?: Array<CustomVariable>;
    'notification_enable'?: UserNotificationEnable | null;
}

