/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CustomVariable } from './custom-variable';
// May contain unused imports in some cases
// @ts-ignore
import type { RoleLimits } from './role-limits';
// May contain unused imports in some cases
// @ts-ignore
import type { UserNotificationEnable } from './user-notification-enable';

export interface AdminModify {
    'password'?: string | null;
    'telegram_id'?: number | null;
    'discord_webhook'?: string | null;
    'status'?: AdminModifyStatusEnum | null;
    'data_limit'?: number | null;
    'sub_template'?: string | null;
    'sub_domain'?: string | null;
    'profile_title'?: string | null;
    'support_url'?: string | null;
    'custom_variables'?: Array<CustomVariable> | null;
    'note'?: string | null;
    'notification_enable'?: UserNotificationEnable | null;
    'role_id'?: number | null;
    'permission_overrides'?: RoleLimits | null;
}

export const AdminModifyStatusEnum = {
    Active: 'active',
    Disabled: 'disabled',
} as const;

export type AdminModifyStatusEnum = typeof AdminModifyStatusEnum[keyof typeof AdminModifyStatusEnum];


