/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AdminRoleData } from './admin-role-data';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminStatus } from './admin-status';
// May contain unused imports in some cases
// @ts-ignore
import type { CustomVariable } from './custom-variable';
// May contain unused imports in some cases
// @ts-ignore
import type { RoleLimits } from './role-limits';
// May contain unused imports in some cases
// @ts-ignore
import type { UserNotificationEnable } from './user-notification-enable';

/**
 * Complete admin model with all fields for database representation and API responses.
 */
export interface AdminDetails {
    'id'?: number | null;
    'username': string;
    'telegram_id'?: number | null;
    'discord_webhook'?: string | null;
    'sub_domain'?: string | null;
    'profile_title'?: string | null;
    'support_url'?: string | null;
    'custom_variables'?: Array<CustomVariable>;
    'notification_enable'?: UserNotificationEnable | null;
    'total_users'?: number;
    'used_traffic'?: number;
    'data_limit'?: number | null;
    'status'?: AdminStatus;
    'sub_template'?: string | null;
    'lifetime_used_traffic'?: number | null;
    'note'?: string | null;
    'role'?: AdminRoleData | null;
    'permission_overrides'?: RoleLimits | null;
    'is_disabled': boolean;
    'is_limited': boolean;
}



