/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Minimal admin model containing only the username.
 * @export
 * @interface AdminBase
 */
export interface AdminBase {
    /**
     * 
     * @type {number}
     * @memberof AdminBase
     */
    'id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AdminBase
     */
    'username': string;
}

