/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdminNotificationEnable
 */
export interface AdminNotificationEnable {
    /**
     * 
     * @type {boolean}
     * @memberof AdminNotificationEnable
     */
    'create'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminNotificationEnable
     */
    'modify'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminNotificationEnable
     */
    'delete'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminNotificationEnable
     */
    'reset_usage'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminNotificationEnable
     */
    'login'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminNotificationEnable
     */
    'usage_limit_warning'?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof AdminNotificationEnable
     */
    'usage_limit_warning_percentages'?: Array<number>;
}

