/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdminRoleSimple
 */
export interface AdminRoleSimple {
    /**
     * 
     * @type {number}
     * @memberof AdminRoleSimple
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof AdminRoleSimple
     */
    'name': string;
    /**
     * 
     * @type {boolean}
     * @memberof AdminRoleSimple
     */
    'is_owner': boolean;
}

