/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AdminRoleSimple } from './admin-role-simple';

/**
 * 
 * @export
 * @interface AdminRolesSimpleResponse
 */
export interface AdminRolesSimpleResponse {
    /**
     * 
     * @type {Array<AdminRoleSimple>}
     * @memberof AdminRolesSimpleResponse
     */
    'roles': Array<AdminRoleSimple>;
    /**
     * 
     * @type {number}
     * @memberof AdminRolesSimpleResponse
     */
    'total': number;
}

