/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AdminRoleData } from './admin-role-data';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminStatus } from './admin-status';
// May contain unused imports in some cases
// @ts-ignore
import type { RoleLimits } from './role-limits';
// May contain unused imports in some cases
// @ts-ignore
import type { UserNotificationEnable } from './user-notification-enable';

/**
 * Complete admin model with all fields for database representation and API responses.
 * @export
 * @interface AdminDetails
 */
export interface AdminDetails {
    /**
     * 
     * @type {number}
     * @memberof AdminDetails
     */
    'id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AdminDetails
     */
    'username': string;
    /**
     * 
     * @type {number}
     * @memberof AdminDetails
     */
    'telegram_id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AdminDetails
     */
    'discord_webhook'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminDetails
     */
    'sub_domain'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminDetails
     */
    'profile_title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminDetails
     */
    'support_url'?: string | null;
    /**
     * 
     * @type {UserNotificationEnable}
     * @memberof AdminDetails
     */
    'notification_enable'?: UserNotificationEnable | null;
    /**
     * 
     * @type {number}
     * @memberof AdminDetails
     */
    'total_users'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminDetails
     */
    'used_traffic'?: number;
    /**
     * 
     * @type {number}
     * @memberof AdminDetails
     */
    'data_limit'?: number | null;
    /**
     * 
     * @type {AdminStatus}
     * @memberof AdminDetails
     */
    'status'?: AdminStatus;
    /**
     * 
     * @type {string}
     * @memberof AdminDetails
     */
    'sub_template'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AdminDetails
     */
    'lifetime_used_traffic'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AdminDetails
     */
    'note'?: string | null;
    /**
     * 
     * @type {AdminRoleData}
     * @memberof AdminDetails
     */
    'role'?: AdminRoleData | null;
    /**
     * 
     * @type {RoleLimits}
     * @memberof AdminDetails
     */
    'permission_overrides'?: RoleLimits | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminDetails
     */
    'is_disabled': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminDetails
     */
    'is_limited': boolean;
}



