/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RoleAccess } from './role-access';
// May contain unused imports in some cases
// @ts-ignore
import type { RoleFeatures } from './role-features';
// May contain unused imports in some cases
// @ts-ignore
import type { RoleHWIDSettings } from './role-hwidsettings';
// May contain unused imports in some cases
// @ts-ignore
import type { RoleLimits } from './role-limits';
// May contain unused imports in some cases
// @ts-ignore
import type { RolePermissions } from './role-permissions';

/**
 * 
 * @export
 * @interface AdminRoleResponse
 */
export interface AdminRoleResponse {
    /**
     * 
     * @type {string}
     * @memberof AdminRoleResponse
     */
    'name': string;
    /**
     * 
     * @type {RolePermissions}
     * @memberof AdminRoleResponse
     */
    'permissions'?: RolePermissions;
    /**
     * 
     * @type {RoleLimits}
     * @memberof AdminRoleResponse
     */
    'limits'?: RoleLimits;
    /**
     * 
     * @type {RoleFeatures}
     * @memberof AdminRoleResponse
     */
    'features'?: RoleFeatures;
    /**
     * 
     * @type {RoleAccess}
     * @memberof AdminRoleResponse
     */
    'access'?: RoleAccess;
    /**
     * 
     * @type {RoleHWIDSettings}
     * @memberof AdminRoleResponse
     */
    'hwid'?: RoleHWIDSettings;
    /**
     * 
     * @type {boolean}
     * @memberof AdminRoleResponse
     */
    'disabled_when_limited'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminRoleResponse
     */
    'disconnect_users_when_limited'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AdminRoleResponse
     */
    'disconnect_users_when_disabled'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AdminRoleResponse
     */
    'id': number;
    /**
     * 
     * @type {boolean}
     * @memberof AdminRoleResponse
     */
    'is_owner': boolean;
    /**
     * 
     * @type {string}
     * @memberof AdminRoleResponse
     */
    'created_at': string;
}

