/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AdminDetails } from './admin-details';

/**
 * Response model for admins list with pagination and statistics.
 */
export interface AdminsResponse {
    'admins': Array<AdminDetails>;
    'total': number;
    'active': number;
    'disabled': number;
    'limited': number;
}

