/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Create } from './create';
// May contain unused imports in some cases
// @ts-ignore
import type { Delete } from './delete';
// May contain unused imports in some cases
// @ts-ignore
import type { Read } from './read';
// May contain unused imports in some cases
// @ts-ignore
import type { ReadSimple } from './read-simple';
// May contain unused imports in some cases
// @ts-ignore
import type { ResetUsage } from './reset-usage';
// May contain unused imports in some cases
// @ts-ignore
import type { Update } from './update';

/**
 * 
 * @export
 * @interface AdminsPermissions
 */
export interface AdminsPermissions {
    [key: string]: any;

    /**
     * 
     * @type {Create}
     * @memberof AdminsPermissions
     */
    'create'?: Create | null;
    /**
     * 
     * @type {Read}
     * @memberof AdminsPermissions
     */
    'read'?: Read | null;
    /**
     * 
     * @type {ReadSimple}
     * @memberof AdminsPermissions
     */
    'read_simple'?: ReadSimple | null;
    /**
     * 
     * @type {Update}
     * @memberof AdminsPermissions
     */
    'update'?: Update | null;
    /**
     * 
     * @type {Delete}
     * @memberof AdminsPermissions
     */
    'delete'?: Delete | null;
    /**
     * 
     * @type {ResetUsage}
     * @memberof AdminsPermissions
     */
    'reset_usage'?: ResetUsage | null;
}

