/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export const APIKeyStatus = {
    Active: 'active',
    Disabled: 'disabled',
} as const;

export type APIKeyStatus = typeof APIKeyStatus[keyof typeof APIKeyStatus];



