/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { APIKeyStatus } from './apikey-status';
// May contain unused imports in some cases
// @ts-ignore
import type { RolePermissions } from './role-permissions';

/**
 * 
 * @export
 * @interface APIKeyResponse
 */
export interface APIKeyResponse {
    /**
     * 
     * @type {string}
     * @memberof APIKeyResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof APIKeyResponse
     */
    'note'?: string | null;
    /**
     * 
     * @type {RolePermissions}
     * @memberof APIKeyResponse
     */
    'permissions'?: RolePermissions;
    /**
     * 
     * @type {boolean}
     * @memberof APIKeyResponse
     */
    'inherit_permissions'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof APIKeyResponse
     */
    'expire_date'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof APIKeyResponse
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof APIKeyResponse
     */
    'admin_id': number;
    /**
     * 
     * @type {string}
     * @memberof APIKeyResponse
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof APIKeyResponse
     */
    'api_key_trimmed': string;
    /**
     * 
     * @type {string}
     * @memberof APIKeyResponse
     */
    'revoked_at'?: string | null;
    /**
     * 
     * @type {APIKeyStatus}
     * @memberof APIKeyResponse
     */
    'status'?: APIKeyStatus;
    /**
     * 
     * @type {boolean}
     * @memberof APIKeyResponse
     */
    'is_expired'?: boolean;
}



