/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { APIKeyStatus } from './apikey-status';
// May contain unused imports in some cases
// @ts-ignore
import type { RolePermissions } from './role-permissions';

export interface APIKeyCreateResponse {
    'name': string;
    'note'?: string | null;
    'permissions'?: RolePermissions;
    'inherit_permissions'?: boolean;
    'expire_date'?: string | null;
    'id': number;
    'admin_id': number;
    'created_at': string;
    'api_key_trimmed': string;
    'revoked_at'?: string | null;
    'status'?: APIKeyStatus;
    'is_expired'?: boolean;
    'api_key': string;
}



