/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { APIKeyStatus } from './apikey-status';
// May contain unused imports in some cases
// @ts-ignore
import type { RolePermissions } from './role-permissions';

/**
 * 
 * @export
 * @interface APIKeyUpdate
 */
export interface APIKeyUpdate {
    /**
     * 
     * @type {number}
     * @memberof APIKeyUpdate
     */
    'admin_id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof APIKeyUpdate
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof APIKeyUpdate
     */
    'note'?: string | null;
    /**
     * 
     * @type {RolePermissions}
     * @memberof APIKeyUpdate
     */
    'permissions'?: RolePermissions | null;
    /**
     * 
     * @type {boolean}
     * @memberof APIKeyUpdate
     */
    'inherit_permissions'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof APIKeyUpdate
     */
    'expire_date'?: string | null;
    /**
     * 
     * @type {APIKeyStatus}
     * @memberof APIKeyUpdate
     */
    'status'?: APIKeyStatus | null;
}



