/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { DownloadLink } from './download-link';
// May contain unused imports in some cases
// @ts-ignore
import type { Platform } from './platform';

export interface Application {
    'name': string;
    'icon_url'?: string;
    'import_url'?: string;
    'description'?: { [key: string]: string; };
    'recommended'?: boolean;
    'show_when_hwid_enabled'?: boolean;
    'platform': Platform;
    'download_links': Array<DownloadLink>;
}



