/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ECHQueryStrategy } from './echquery-strategy';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMask } from './final-mask';
// May contain unused imports in some cases
// @ts-ignore
import type { FragmentSettings } from './fragment-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { MuxSettingsOutput } from './mux-settings-output';
// May contain unused imports in some cases
// @ts-ignore
import type { NoiseSettings } from './noise-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { ProxyHostALPN } from './proxy-host-alpn';
// May contain unused imports in some cases
// @ts-ignore
import type { ProxyHostFingerprint } from './proxy-host-fingerprint';
// May contain unused imports in some cases
// @ts-ignore
import type { ProxyHostSecurity } from './proxy-host-security';
// May contain unused imports in some cases
// @ts-ignore
import type { SubscriptionTemplates } from './subscription-templates';
// May contain unused imports in some cases
// @ts-ignore
import type { TransportSettings } from './transport-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { UserStatus } from './user-status';
// May contain unused imports in some cases
// @ts-ignore
import type { WireGuardHostOverrides } from './wire-guard-host-overrides';

export interface BaseHost {
    'id'?: number | null;
    'remark': string;
    'address'?: Set<string>;
    'inbound_tag'?: string | null;
    'port'?: number | null;
    'sni'?: Set<string> | null;
    'host'?: Set<string> | null;
    'path'?: string | null;
    'security'?: ProxyHostSecurity;
    'alpn'?: Array<ProxyHostALPN> | null;
    'fingerprint'?: ProxyHostFingerprint;
    'allowinsecure'?: boolean | null;
    'is_disabled'?: boolean;
    'http_headers'?: { [key: string]: string; } | null;
    'transport_settings'?: TransportSettings | null;
    'mux_settings'?: MuxSettingsOutput | null;
    'fragment_settings'?: FragmentSettings | null;
    'noise_settings'?: NoiseSettings | null;
    'random_user_agent'?: boolean;
    'use_sni_as_host'?: boolean;
    'vless_route'?: string | null;
    'priority': number;
    'status'?: Set<UserStatus> | null;
    'ech_config_list'?: string | null;
    'ech_query_strategy'?: ECHQueryStrategy | null;
    'pinned_peer_cert_sha256'?: string | null;
    'verify_peer_cert_by_name'?: Set<string> | null;
    'wireguard_overrides'?: WireGuardHostOverrides | null;
    'subscription_templates'?: SubscriptionTemplates | null;
    'final_mask_settings'?: FinalMask | null;
}



