/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Apply a user template to a selection of existing users (by ID).
 */
export interface BulkUsersApplyTemplate {
    'user_template_id': number;
    'note'?: string | null;
    'ids'?: Set<number>;
}

