/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Model for bulk client template selection by IDs
 * @export
 * @interface BulkClientTemplateSelection
 */
export interface BulkClientTemplateSelection {
    /**
     * 
     * @type {Set<number>}
     * @memberof BulkClientTemplateSelection
     */
    'ids'?: Set<number>;
}

