/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 3.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserStatus } from './user-status';

/**
 * Re-seat WireGuard peer IPs (same scoping as BulkUser: users, admins, group_ids, status).
 * @export
 * @interface BulkWireGuardPeerIPs
 */
export interface BulkWireGuardPeerIPs {
    /**
     * 
     * @type {boolean}
     * @memberof BulkWireGuardPeerIPs
     */
    'confirm'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BulkWireGuardPeerIPs
     */
    'dry_run'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BulkWireGuardPeerIPs
     */
    'replace_all'?: boolean;
    /**
     * 
     * @type {Set<number>}
     * @memberof BulkWireGuardPeerIPs
     */
    'group_ids'?: Set<number>;
    /**
     * 
     * @type {Set<number>}
     * @memberof BulkWireGuardPeerIPs
     */
    'admins'?: Set<number>;
    /**
     * 
     * @type {Set<number>}
     * @memberof BulkWireGuardPeerIPs
     */
    'users'?: Set<number>;
    /**
     * 
     * @type {Set<UserStatus>}
     * @memberof BulkWireGuardPeerIPs
     */
    'status'?: Set<UserStatus>;
}

