/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 4.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Apply a user template to a selection of existing users (by ID).
 * @export
 * @interface BulkUsersApplyTemplate
 */
export interface BulkUsersApplyTemplate {
    /**
     * 
     * @type {number}
     * @memberof BulkUsersApplyTemplate
     */
    'user_template_id': number;
    /**
     * 
     * @type {string}
     * @memberof BulkUsersApplyTemplate
     */
    'note'?: string | null;
    /**
     * 
     * @type {Set<number>}
     * @memberof BulkUsersApplyTemplate
     */
    'ids'?: Set<number>;
}

