/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Model for bulk API key selection by IDs.
 * @export
 * @interface BulkAPIKeySelection
 */
export interface BulkAPIKeySelection {
    /**
     * 
     * @type {Set<number>}
     * @memberof BulkAPIKeySelection
     */
    'ids'?: Set<number>;
}

