/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ShadowsocksMethods } from './shadowsocks-methods';
// May contain unused imports in some cases
// @ts-ignore
import type { UserStatus } from './user-status';

/**
 * 
 * @export
 * @interface BulkUsersProxy
 */
export interface BulkUsersProxy {
    /**
     * 
     * @type {boolean}
     * @memberof BulkUsersProxy
     */
    'dry_run'?: boolean;
    /**
     * 
     * @type {Set<number>}
     * @memberof BulkUsersProxy
     */
    'group_ids'?: Set<number>;
    /**
     * 
     * @type {Set<number>}
     * @memberof BulkUsersProxy
     */
    'admins'?: Set<number>;
    /**
     * 
     * @type {Set<number>}
     * @memberof BulkUsersProxy
     */
    'users'?: Set<number>;
    /**
     * 
     * @type {Set<UserStatus>}
     * @memberof BulkUsersProxy
     */
    'status'?: Set<UserStatus>;
    /**
     * 
     * @type {string}
     * @memberof BulkUsersProxy
     */
    'expire_after'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BulkUsersProxy
     */
    'expire_before'?: string | null;
    /**
     * 
     * @type {ShadowsocksMethods}
     * @memberof BulkUsersProxy
     */
    'method'?: ShadowsocksMethods | null;
}



