/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Model for bulk user template selection by IDs
 * @export
 * @interface BulkUserTemplateSelection
 */
export interface BulkUserTemplateSelection {
    /**
     * 
     * @type {Set<number>}
     * @memberof BulkUserTemplateSelection
     */
    'ids'?: Set<number>;
}

