/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 3.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Model for bulk admin selection by usernames
 * @export
 * @interface BulkAdminSelection
 */
export interface BulkAdminSelection {
    /**
     * 
     * @type {Set<string>}
     * @memberof BulkAdminSelection
     */
    'usernames'?: Set<string>;
}

