/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 4.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BulkUsersSetOwner
 */
export interface BulkUsersSetOwner {
    /**
     * 
     * @type {Set<number>}
     * @memberof BulkUsersSetOwner
     */
    'ids'?: Set<number>;
    /**
     * 
     * @type {string}
     * @memberof BulkUsersSetOwner
     */
    'admin_username': string;
}

