/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BulkUsersActionResponse
 */
export interface BulkUsersActionResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkUsersActionResponse
     */
    'users': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof BulkUsersActionResponse
     */
    'count': number;
}

