/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BulkGroup {
    'group_ids': Set<number>;
    'has_group_ids'?: Set<number>;
    'admins'?: Set<number>;
    'users'?: Set<number>;
    'dry_run'?: boolean;
}

