/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 3.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response model for bulk group actions.
 * @export
 * @interface BulkGroupsActionResponse
 */
export interface BulkGroupsActionResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof BulkGroupsActionResponse
     */
    'groups': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof BulkGroupsActionResponse
     */
    'count': number;
}

