/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { UsernameGenerationStrategy } from './username-generation-strategy';

export interface BulkUsersFromTemplate {
    'user_template_id': number;
    'note'?: string | null;
    'username'?: string | null;
    'count': number;
    'strategy'?: UsernameGenerationStrategy;
    /**
     * Starting suffix for sequence strategy (defaults to 1; base username digits are ignored)
     */
    'start_number'?: number | null;
}



