/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Brutal } from './brutal';
// May contain unused imports in some cases
// @ts-ignore
import type { MultiplexProtocol } from './multiplex-protocol';

export interface ClashMuxSettings {
    'enable'?: boolean;
    'protocol'?: MultiplexProtocol;
    'max_connections'?: number | null;
    'max_streams'?: number | null;
    'min_streams'?: number | null;
    'padding'?: boolean;
    'brutal'?: Brutal | null;
    'statistic'?: boolean;
    'only_tcp'?: boolean;
}



