/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 3.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ClientTemplateType } from './client-template-type';

/**
 * 
 * @export
 * @interface ClientTemplateSimple
 */
export interface ClientTemplateSimple {
    /**
     * 
     * @type {number}
     * @memberof ClientTemplateSimple
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ClientTemplateSimple
     */
    'name': string;
    /**
     * 
     * @type {ClientTemplateType}
     * @memberof ClientTemplateSimple
     */
    'template_type': ClientTemplateType;
    /**
     * 
     * @type {boolean}
     * @memberof ClientTemplateSimple
     */
    'is_default': boolean;
}



