/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 3.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ClientTemplateModify
 */
export interface ClientTemplateModify {
    /**
     * 
     * @type {string}
     * @memberof ClientTemplateModify
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClientTemplateModify
     */
    'content'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ClientTemplateModify
     */
    'is_default'?: boolean | null;
}

