/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CoreType } from './core-type';

/**
 * Lightweight core model with only id, name and type for performance.
 * @export
 * @interface CoreSimple
 */
export interface CoreSimple {
    /**
     * 
     * @type {number}
     * @memberof CoreSimple
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof CoreSimple
     */
    'name': string;
    /**
     * 
     * @type {CoreType}
     * @memberof CoreSimple
     */
    'type'?: CoreType | null;
}



