/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CoreType } from './core-type';

/**
 * 
 * @export
 * @interface CoreCreate
 */
export interface CoreCreate {
    /**
     * 
     * @type {string}
     * @memberof CoreCreate
     */
    'name'?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CoreCreate
     */
    'config': { [key: string]: any; };
    /**
     * 
     * @type {CoreType}
     * @memberof CoreCreate
     */
    'type'?: CoreType | null;
    /**
     * 
     * @type {Set<any>}
     * @memberof CoreCreate
     */
    'exclude_inbound_tags'?: Set<any> | null;
    /**
     * 
     * @type {Set<any>}
     * @memberof CoreCreate
     */
    'fallbacks_inbound_tags'?: Set<any> | null;
}



