/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const CoreType = {
    Xray: 'xray',
    Wg: 'wg',
    Mtproto: 'mtproto',
    Singbox: 'singbox'
} as const;

export type CoreType = typeof CoreType[keyof typeof CoreType];



