/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Lightweight core model with only id and name for performance.
 * @export
 * @interface CoreSimple
 */
export interface CoreSimple {
    /**
     * 
     * @type {number}
     * @memberof CoreSimple
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof CoreSimple
     */
    'name': string;
}

