/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Create } from './create';
// May contain unused imports in some cases
// @ts-ignore
import type { Delete } from './delete';
// May contain unused imports in some cases
// @ts-ignore
import type { Read } from './read';
// May contain unused imports in some cases
// @ts-ignore
import type { ReadSimple } from './read-simple';
// May contain unused imports in some cases
// @ts-ignore
import type { Update } from './update';

/**
 * Standard create/read/read_simple/update/delete permissions. Used directly by: groups, templates, client_templates, cores, admin_roles. Also serves as base for resources with additional actions.
 * @export
 * @interface CRUDPermissions
 */
export interface CRUDPermissions {
    [key: string]: any;

    /**
     * 
     * @type {Create}
     * @memberof CRUDPermissions
     */
    'create'?: Create | null;
    /**
     * 
     * @type {Read}
     * @memberof CRUDPermissions
     */
    'read'?: Read | null;
    /**
     * 
     * @type {ReadSimple}
     * @memberof CRUDPermissions
     */
    'read_simple'?: ReadSimple | null;
    /**
     * 
     * @type {Update}
     * @memberof CRUDPermissions
     */
    'update'?: Update | null;
    /**
     * 
     * @type {Delete}
     * @memberof CRUDPermissions
     */
    'delete'?: Delete | null;
}

