/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export const ECHQueryStrategy = {
    None: 'none',
    Half: 'half',
    Full: 'full',
} as const;

export type ECHQueryStrategy = typeof ECHQueryStrategy[keyof typeof ECHQueryStrategy];



