/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const FinalMaskQuicCongestion = {
    Reno: 'reno',
    Bbr: 'bbr',
    Brutal: 'brutal',
    ForceBrutal: 'force-brutal'
} as const;

export type FinalMaskQuicCongestion = typeof FinalMaskQuicCongestion[keyof typeof FinalMaskQuicCongestion];



