/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const FinalMaskTcpType = {
    HeaderCustom: 'header-custom',
    Fragment: 'fragment',
    Sudoku: 'sudoku'
} as const;

export type FinalMaskTcpType = typeof FinalMaskTcpType[keyof typeof FinalMaskTcpType];



