/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { XrayNoiseSettings } from './xray-noise-settings';

export interface FinalMaskTcpHeaderCustomSettings {
    [key: string]: any;

    'clients'?: Array<Array<XrayNoiseSettings>> | null;
    'servers'?: Array<Array<XrayNoiseSettings>> | null;
    'errors'?: Array<Array<XrayNoiseSettings>> | null;
}

