/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Interval } from './interval';

/**
 * 
 * @export
 * @interface FinalMaskUdpHop
 */
export interface FinalMaskUdpHop {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof FinalMaskUdpHop
     */
    'ports'?: string | null;
    /**
     * 
     * @type {Interval}
     * @memberof FinalMaskUdpHop
     */
    'interval'?: Interval | null;
}

