/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Brutaldown } from './brutaldown';
// May contain unused imports in some cases
// @ts-ignore
import type { Brutalup } from './brutalup';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskQuicCongestion } from './final-mask-quic-congestion';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskUdpHop } from './final-mask-udp-hop';

export interface FinalMaskQuicParams {
    [key: string]: any;

    'congestion'?: FinalMaskQuicCongestion | null;
    'debug'?: boolean | null;
    'bbrProfile'?: string | null;
    'brutalUp'?: Brutalup | null;
    'brutalDown'?: Brutaldown | null;
    'udpHop'?: FinalMaskUdpHop | null;
    'initStreamReceiveWindow'?: number | null;
    'maxStreamReceiveWindow'?: number | null;
    'initConnectionReceiveWindow'?: number | null;
    'maxConnectionReceiveWindow'?: number | null;
    'maxIdleTimeout'?: number | null;
    'keepAlivePeriod'?: number | null;
    'disablePathMTUDiscovery'?: boolean | null;
    'maxIncomingStreams'?: number | null;
}



