/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export const FinalMaskUdpType = {
    HeaderCustom: 'header-custom',
    MkcpLegacy: 'mkcp-legacy',
    Noise: 'noise',
    Salamander: 'salamander',
    Sudoku: 'sudoku',
    Xdns: 'xdns',
    Xicmp: 'xicmp',
    Realm: 'realm',
    HeaderDns: 'header-dns',
    HeaderDtls: 'header-dtls',
    HeaderSrtp: 'header-srtp',
    HeaderUtp: 'header-utp',
    HeaderWechat: 'header-wechat',
    HeaderWireguard: 'header-wireguard',
    MkcpOriginal: 'mkcp-original',
    MkcpAes128gcm: 'mkcp-aes128gcm',
} as const;

export type FinalMaskUdpType = typeof FinalMaskUdpType[keyof typeof FinalMaskUdpType];



