/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Brutaldown } from './brutaldown';
// May contain unused imports in some cases
// @ts-ignore
import type { Brutalup } from './brutalup';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskQuicCongestion } from './final-mask-quic-congestion';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskUdpHop } from './final-mask-udp-hop';

/**
 * 
 * @export
 * @interface FinalMaskQuicParams
 */
export interface FinalMaskQuicParams {
    [key: string]: any;

    /**
     * 
     * @type {FinalMaskQuicCongestion}
     * @memberof FinalMaskQuicParams
     */
    'congestion'?: FinalMaskQuicCongestion | null;
    /**
     * 
     * @type {boolean}
     * @memberof FinalMaskQuicParams
     */
    'debug'?: boolean | null;
    /**
     * 
     * @type {Brutalup}
     * @memberof FinalMaskQuicParams
     */
    'brutalUp'?: Brutalup | null;
    /**
     * 
     * @type {Brutaldown}
     * @memberof FinalMaskQuicParams
     */
    'brutalDown'?: Brutaldown | null;
    /**
     * 
     * @type {FinalMaskUdpHop}
     * @memberof FinalMaskQuicParams
     */
    'udpHop'?: FinalMaskUdpHop | null;
    /**
     * 
     * @type {number}
     * @memberof FinalMaskQuicParams
     */
    'initStreamReceiveWindow'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FinalMaskQuicParams
     */
    'maxStreamReceiveWindow'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FinalMaskQuicParams
     */
    'initConnectionReceiveWindow'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FinalMaskQuicParams
     */
    'maxConnectionReceiveWindow'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FinalMaskQuicParams
     */
    'maxIdleTimeout'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FinalMaskQuicParams
     */
    'keepAlivePeriod'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof FinalMaskQuicParams
     */
    'disablePathMTUDiscovery'?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof FinalMaskQuicParams
     */
    'maxIncomingStreams'?: number | null;
}



