/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { SingBoxFragmentSettings } from './sing-box-fragment-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { XrayFragmentSettings } from './xray-fragment-settings';

export interface FragmentSettings {
    'xray'?: XrayFragmentSettings | null;
    'sing_box'?: SingBoxFragmentSettings | null;
}

