/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SingBoxFragmentSettings } from './sing-box-fragment-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { XrayFragmentSettingsOutput } from './xray-fragment-settings-output';

/**
 * 
 * @export
 * @interface FragmentSettingsOutput
 */
export interface FragmentSettingsOutput {
    /**
     * 
     * @type {XrayFragmentSettingsOutput}
     * @memberof FragmentSettingsOutput
     */
    'xray'?: XrayFragmentSettingsOutput | null;
    /**
     * 
     * @type {SingBoxFragmentSettings}
     * @memberof FragmentSettingsOutput
     */
    'sing_box'?: SingBoxFragmentSettings | null;
}

