/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SingBoxFragmentSettings } from './sing-box-fragment-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { XrayFragmentSettingsInput } from './xray-fragment-settings-input';

/**
 * 
 * @export
 * @interface FragmentSettingsInput
 */
export interface FragmentSettingsInput {
    /**
     * 
     * @type {XrayFragmentSettingsInput}
     * @memberof FragmentSettingsInput
     */
    'xray'?: XrayFragmentSettingsInput | null;
    /**
     * 
     * @type {SingBoxFragmentSettings}
     * @memberof FragmentSettingsInput
     */
    'sing_box'?: SingBoxFragmentSettings | null;
}

