/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CustomVariable } from './custom-variable';
// May contain unused imports in some cases
// @ts-ignore
import type { ShadowsocksMethods } from './shadowsocks-methods';

export interface General {
    'default_method'?: ShadowsocksMethods;
    'custom_variables'?: Array<CustomVariable> | null;
}



