/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Lightweight group model with only id and name for performance.
 * @export
 * @interface GroupSimple
 */
export interface GroupSimple {
    /**
     * 
     * @type {number}
     * @memberof GroupSimple
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof GroupSimple
     */
    'name': string;
}

