/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GroupSimple } from './group-simple';

/**
 * Response model for lightweight group list.
 * @export
 * @interface GroupsSimpleResponse
 */
export interface GroupsSimpleResponse {
    /**
     * 
     * @type {Array<GroupSimple>}
     * @memberof GroupsSimpleResponse
     */
    'groups': Array<GroupSimple>;
    /**
     * 
     * @type {number}
     * @memberof GroupsSimpleResponse
     */
    'total': number;
}

