/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GRPCSettings {
    'multi_mode'?: boolean;
    'idle_timeout'?: number | null;
    'health_check_timeout'?: number | null;
    'permit_without_stream'?: boolean;
    'initial_windows_size'?: number | null;
}

