/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const HWIDMode = {
    Disabled: 'disabled',
    UseGlobal: 'use_global',
    Override: 'override'
} as const;

export type HWIDMode = typeof HWIDMode[keyof typeof HWIDMode];



