/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Delete } from './delete';
// May contain unused imports in some cases
// @ts-ignore
import type { Read } from './read';

/**
 * 
 * @export
 * @interface HwidsPermissions
 */
export interface HwidsPermissions {
    [key: string]: any;

    /**
     * 
     * @type {Read}
     * @memberof HwidsPermissions
     */
    'read'?: Read | null;
    /**
     * 
     * @type {Delete}
     * @memberof HwidsPermissions
     */
    'delete'?: Delete | null;
}

