/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 4.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HWIDSettings
 */
export interface HWIDSettings {
    /**
     * 
     * @type {boolean}
     * @memberof HWIDSettings
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HWIDSettings
     */
    'forced'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof HWIDSettings
     */
    'fallback_limit'?: number;
    /**
     * 
     * @type {number}
     * @memberof HWIDSettings
     */
    'min_limit'?: number;
    /**
     * 
     * @type {number}
     * @memberof HWIDSettings
     */
    'max_limit'?: number;
}

