/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InboundSummary
 */
export interface InboundSummary {
    /**
     * 
     * @type {string}
     * @memberof InboundSummary
     */
    'tag': string;
    /**
     * 
     * @type {string}
     * @memberof InboundSummary
     */
    'protocol': string;
    /**
     * 
     * @type {string}
     * @memberof InboundSummary
     */
    'network'?: string | null;
}

