/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface KCPSettings
 */
export interface KCPSettings {
    /**
     * 
     * @type {number}
     * @memberof KCPSettings
     */
    'mtu'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof KCPSettings
     */
    'tti'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof KCPSettings
     */
    'uplink_capacity'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof KCPSettings
     */
    'downlink_capacity'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof KCPSettings
     */
    'congestion'?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof KCPSettings
     */
    'read_buffer_size'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof KCPSettings
     */
    'write_buffer_size'?: number | null;
}

