/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KCPSettings {
    'mtu'?: number | null;
    'tti'?: number | null;
    'uplink_capacity'?: number | null;
    'downlink_capacity'?: number | null;
    'congestion'?: boolean | null;
    'read_buffer_size'?: number | null;
    'write_buffer_size'?: number | null;
}

