/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NextPlanModel {
    'user_template_id'?: number | null;
    'data_limit'?: number | null;
    'expire'?: number | null;
    'add_remaining_traffic'?: boolean;
}

