/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 4.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NodeOutboundLatency
 */
export interface NodeOutboundLatency {
    /**
     * 
     * @type {string}
     * @memberof NodeOutboundLatency
     */
    'name': string;
    /**
     * 
     * @type {boolean}
     * @memberof NodeOutboundLatency
     */
    'alive': boolean;
    /**
     * 
     * @type {number}
     * @memberof NodeOutboundLatency
     */
    'delay': number;
    /**
     * 
     * @type {string}
     * @memberof NodeOutboundLatency
     */
    'link': string;
    /**
     * 
     * @type {number}
     * @memberof NodeOutboundLatency
     */
    'last_seen_time': number;
    /**
     * 
     * @type {number}
     * @memberof NodeOutboundLatency
     */
    'last_try_time': number;
    /**
     * 
     * @type {string}
     * @memberof NodeOutboundLatency
     */
    'source': string;
}

