/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NodeSimple } from './node-simple';

/**
 * Response model for lightweight node list.
 * @export
 * @interface NodesSimpleResponse
 */
export interface NodesSimpleResponse {
    /**
     * 
     * @type {Array<NodeSimple>}
     * @memberof NodesSimpleResponse
     */
    'nodes': Array<NodeSimple>;
    /**
     * 
     * @type {number}
     * @memberof NodesSimpleResponse
     */
    'total': number;
}

