/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Create } from './create';
// May contain unused imports in some cases
// @ts-ignore
import type { Delete } from './delete';
// May contain unused imports in some cases
// @ts-ignore
import type { Logs } from './logs';
// May contain unused imports in some cases
// @ts-ignore
import type { Read } from './read';
// May contain unused imports in some cases
// @ts-ignore
import type { ReadSimple } from './read-simple';
// May contain unused imports in some cases
// @ts-ignore
import type { Reconnect } from './reconnect';
// May contain unused imports in some cases
// @ts-ignore
import type { Stats } from './stats';
// May contain unused imports in some cases
// @ts-ignore
import type { Update } from './update';
// May contain unused imports in some cases
// @ts-ignore
import type { UpdateCore } from './update-core';

/**
 * 
 * @export
 * @interface NodesPermissions
 */
export interface NodesPermissions {
    [key: string]: any;

    /**
     * 
     * @type {Create}
     * @memberof NodesPermissions
     */
    'create'?: Create | null;
    /**
     * 
     * @type {Read}
     * @memberof NodesPermissions
     */
    'read'?: Read | null;
    /**
     * 
     * @type {ReadSimple}
     * @memberof NodesPermissions
     */
    'read_simple'?: ReadSimple | null;
    /**
     * 
     * @type {Update}
     * @memberof NodesPermissions
     */
    'update'?: Update | null;
    /**
     * 
     * @type {Delete}
     * @memberof NodesPermissions
     */
    'delete'?: Delete | null;
    /**
     * 
     * @type {Reconnect}
     * @memberof NodesPermissions
     */
    'reconnect'?: Reconnect | null;
    /**
     * 
     * @type {UpdateCore}
     * @memberof NodesPermissions
     */
    'update_core'?: UpdateCore | null;
    /**
     * 
     * @type {Logs}
     * @memberof NodesPermissions
     */
    'logs'?: Logs | null;
    /**
     * 
     * @type {Stats}
     * @memberof NodesPermissions
     */
    'stats'?: Stats | null;
}

