/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NodeRealtimeStats {
    'mem_total': number;
    'mem_used': number;
    'cpu_cores': number;
    'cpu_usage': number;
    'incoming_bandwidth_speed': number;
    'outgoing_bandwidth_speed': number;
    'uptime': number;
}

