/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { DataLimitResetStrategy } from './data-limit-reset-strategy';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeConnectionType } from './node-connection-type';

export interface NodeCreate {
    'name': string;
    'address': string;
    'port'?: number;
    'api_port'?: number;
    'usage_coefficient'?: number;
    'connection_type': NodeConnectionType;
    'server_ca': string;
    'keep_alive': number;
    'core_config_id': number;
    'api_key': string;
    'data_limit'?: number;
    'data_limit_reset_strategy'?: DataLimitResetStrategy;
    'reset_time'?: number;
    'default_timeout'?: number;
    'internal_timeout'?: number;
    'proxy_url'?: string | null;
}



