/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { DataLimitResetStrategy } from './data-limit-reset-strategy';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeConnectionType } from './node-connection-type';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeStatus } from './node-status';

export interface NodeModify {
    'name'?: string | null;
    'address'?: string | null;
    'port'?: number | null;
    'api_port'?: number;
    'usage_coefficient'?: number | null;
    'connection_type'?: NodeConnectionType | null;
    'server_ca'?: string | null;
    'keep_alive'?: number | null;
    'core_config_id'?: number | null;
    'api_key'?: string | null;
    'data_limit'?: number | null;
    'data_limit_reset_strategy'?: DataLimitResetStrategy | null;
    'reset_time'?: number | null;
    'default_timeout'?: number | null;
    'internal_timeout'?: number | null;
    'proxy_url'?: string | null;
    'status'?: NodeStatus | null;
}



