/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NodeStatus } from './node-status';

/**
 * Lightweight node model with only id and name for performance.
 * @export
 * @interface NodeSimple
 */
export interface NodeSimple {
    /**
     * 
     * @type {number}
     * @memberof NodeSimple
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof NodeSimple
     */
    'name': string;
    /**
     * 
     * @type {NodeStatus}
     * @memberof NodeSimple
     */
    'status': NodeStatus;
}



