/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Create } from './create';
// May contain unused imports in some cases
// @ts-ignore
import type { Delete } from './delete';
// May contain unused imports in some cases
// @ts-ignore
import type { Logs } from './logs';
// May contain unused imports in some cases
// @ts-ignore
import type { Read } from './read';
// May contain unused imports in some cases
// @ts-ignore
import type { ReadSimple } from './read-simple';
// May contain unused imports in some cases
// @ts-ignore
import type { Reconnect } from './reconnect';
// May contain unused imports in some cases
// @ts-ignore
import type { Stats } from './stats';
// May contain unused imports in some cases
// @ts-ignore
import type { Update } from './update';
// May contain unused imports in some cases
// @ts-ignore
import type { UpdateCore } from './update-core';

export interface NodesPermissions {
    'create'?: Create | null;
    'read'?: Read | null;
    'read_simple'?: ReadSimple | null;
    'update'?: Update | null;
    'delete'?: Delete | null;
    'reconnect'?: Reconnect | null;
    'update_core'?: UpdateCore | null;
    'logs'?: Logs | null;
    'stats'?: Stats | null;
}

