/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Channel configuration for sending notifications to a specific entity
 */
export interface NotificationChannel {
    'telegram_chat_id'?: number | null;
    'telegram_topic_id'?: number | null;
    'discord_webhook_url'?: string | null;
}

