/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { NotificationChannels } from './notification-channels';

export interface NotificationSettings {
    'notify_telegram'?: boolean;
    'notify_discord'?: boolean;
    'telegram_api_token'?: string | null;
    'telegram_chat_id'?: number | null;
    'telegram_topic_id'?: number | null;
    'discord_webhook_url'?: string | null;
    'channels'?: NotificationChannels;
    'proxy_url'?: string | null;
    'max_retries': number;
}

