/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NotificationChannels } from './notification-channels';

/**
 * 
 * @export
 * @interface NotificationSettings
 */
export interface NotificationSettings {
    /**
     * 
     * @type {boolean}
     * @memberof NotificationSettings
     */
    'notify_telegram'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationSettings
     */
    'notify_discord'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NotificationSettings
     */
    'telegram_api_token'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NotificationSettings
     */
    'telegram_chat_id'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NotificationSettings
     */
    'telegram_topic_id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof NotificationSettings
     */
    'discord_webhook_url'?: string | null;
    /**
     * 
     * @type {NotificationChannels}
     * @memberof NotificationSettings
     */
    'channels'?: NotificationChannels;
    /**
     * 
     * @type {string}
     * @memberof NotificationSettings
     */
    'proxy_url'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NotificationSettings
     */
    'max_retries': number;
}

