/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OwnerResetRequest
 */
export interface OwnerResetRequest {
    /**
     * 
     * @type {string}
     * @memberof OwnerResetRequest
     */
    'key': string;
    /**
     * 
     * @type {string}
     * @memberof OwnerResetRequest
     */
    'password': string;
}

