/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Scope for user-resource permissions. Stored as int in JSON for efficiency.
 */

export const PermissionScope = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
} as const;

export type PermissionScope = typeof PermissionScope[keyof typeof PermissionScope];



