/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HysteriaSettings } from './hysteria-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { ShadowsocksSettings } from './shadowsocks-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { TrojanSettings } from './trojan-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { VMessSettings } from './vmess-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { VlessSettings } from './vless-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { WireGuardSettings } from './wire-guard-settings';

/**
 * 
 * @export
 * @interface ProxyTableOutput
 */
export interface ProxyTableOutput {
    /**
     * 
     * @type {VMessSettings}
     * @memberof ProxyTableOutput
     */
    'vmess'?: VMessSettings;
    /**
     * 
     * @type {VlessSettings}
     * @memberof ProxyTableOutput
     */
    'vless'?: VlessSettings;
    /**
     * 
     * @type {TrojanSettings}
     * @memberof ProxyTableOutput
     */
    'trojan'?: TrojanSettings;
    /**
     * 
     * @type {ShadowsocksSettings}
     * @memberof ProxyTableOutput
     */
    'shadowsocks'?: ShadowsocksSettings;
    /**
     * 
     * @type {WireGuardSettings}
     * @memberof ProxyTableOutput
     */
    'wireguard'?: WireGuardSettings;
    /**
     * 
     * @type {HysteriaSettings}
     * @memberof ProxyTableOutput
     */
    'hysteria'?: HysteriaSettings;
}

