/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RealityScanRequest {
    /**
     * host or host:port to probe (port defaults to 443)
     */
    'target': string;
    /**
     * Per-probe timeout in seconds (1-20, default 10)
     */
    'timeout'?: number | null;
}

