/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 4.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response model for bulk node deletion
 * @export
 * @interface RemoveNodesResponse
 */
export interface RemoveNodesResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof RemoveNodesResponse
     */
    'nodes': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof RemoveNodesResponse
     */
    'count': number;
}

