/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { APIKeysPermissions } from './apikeys-permissions';
// May contain unused imports in some cases
// @ts-ignore
import type { AdminsPermissions } from './admins-permissions';
// May contain unused imports in some cases
// @ts-ignore
import type { CRUDPermissions } from './crudpermissions';
// May contain unused imports in some cases
// @ts-ignore
import type { HostsPermissions } from './hosts-permissions';
// May contain unused imports in some cases
// @ts-ignore
import type { HwidsPermissions } from './hwids-permissions';
// May contain unused imports in some cases
// @ts-ignore
import type { NodesPermissions } from './nodes-permissions';
// May contain unused imports in some cases
// @ts-ignore
import type { SettingsPermissions } from './settings-permissions';
// May contain unused imports in some cases
// @ts-ignore
import type { SystemPermissions } from './system-permissions';
// May contain unused imports in some cases
// @ts-ignore
import type { UsersPermissions } from './users-permissions';

/**
 * Typed permission map. Missing resource or action = denied. Each action value is True (allowed), {\"scope\": N} (scoped), or None (denied).
 */
export interface RolePermissions {
    'users'?: UsersPermissions | null;
    'admins'?: AdminsPermissions | null;
    'nodes'?: NodesPermissions | null;
    'groups'?: CRUDPermissions | null;
    'hosts'?: HostsPermissions | null;
    'templates'?: CRUDPermissions | null;
    'client_templates'?: CRUDPermissions | null;
    'cores'?: CRUDPermissions | null;
    'settings'?: SettingsPermissions | null;
    'system'?: SystemPermissions | null;
    'hwids'?: HwidsPermissions | null;
    'admin_roles'?: CRUDPermissions | null;
    'api_keys'?: APIKeysPermissions | null;
}

