/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoleLimits {
    'max_users'?: number | null;
    'data_limit_min'?: number | null;
    'data_limit_max'?: number | null;
    'expire_min'?: number | null;
    'expire_max'?: number | null;
    'min_hwid_per_user'?: number | null;
    'max_hwid_per_user'?: number | null;
    'on_hold_timeout_min'?: number | null;
    'on_hold_timeout_max'?: number | null;
}

