/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RoleFeatures
 */
export interface RoleFeatures {
    /**
     * 
     * @type {boolean}
     * @memberof RoleFeatures
     */
    'can_use_reset_strategy'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RoleFeatures
     */
    'can_use_next_plan'?: boolean;
}

