/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RoleLimits
 */
export interface RoleLimits {
    /**
     * 
     * @type {number}
     * @memberof RoleLimits
     */
    'max_users'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RoleLimits
     */
    'data_limit_min'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RoleLimits
     */
    'data_limit_max'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RoleLimits
     */
    'expire_min'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RoleLimits
     */
    'expire_max'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RoleLimits
     */
    'min_hwid_per_user'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RoleLimits
     */
    'max_hwid_per_user'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RoleLimits
     */
    'on_hold_timeout_min'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RoleLimits
     */
    'on_hold_timeout_max'?: number | null;
}

