/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HWIDMode } from './hwidmode';

/**
 * 
 * @export
 * @interface RoleHWIDSettings
 */
export interface RoleHWIDSettings {
    /**
     * 
     * @type {boolean}
     * @memberof RoleHWIDSettings
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RoleHWIDSettings
     */
    'forced'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RoleHWIDSettings
     */
    'require_hwid_for_manual_sub'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RoleHWIDSettings
     */
    'fallback_limit'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RoleHWIDSettings
     */
    'min_limit'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RoleHWIDSettings
     */
    'max_limit'?: number | null;
    /**
     * 
     * @type {HWIDMode}
     * @memberof RoleHWIDSettings
     */
    'mode'?: HWIDMode;
}



