/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { HWIDMode } from './hwidmode';

export interface RoleHWIDSettings {
    'enabled'?: boolean;
    'forced'?: boolean;
    'require_hwid_for_manual_sub'?: boolean;
    'fallback_limit'?: number | null;
    'min_limit'?: number | null;
    'max_limit'?: number | null;
    'mode'?: HWIDMode;
}



