/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AdminsPermissions } from './admins-permissions';
// May contain unused imports in some cases
// @ts-ignore
import type { CRUDPermissions } from './crudpermissions';
// May contain unused imports in some cases
// @ts-ignore
import type { HostsPermissions } from './hosts-permissions';
// May contain unused imports in some cases
// @ts-ignore
import type { HwidsPermissions } from './hwids-permissions';
// May contain unused imports in some cases
// @ts-ignore
import type { NodesPermissions } from './nodes-permissions';
// May contain unused imports in some cases
// @ts-ignore
import type { SettingsPermissions } from './settings-permissions';
// May contain unused imports in some cases
// @ts-ignore
import type { SystemPermissions } from './system-permissions';
// May contain unused imports in some cases
// @ts-ignore
import type { UsersPermissions } from './users-permissions';

/**
 * Typed permission map. Missing resource or action = denied. Each action value is True (allowed), {\"scope\": N} (scoped), or None (denied).
 * @export
 * @interface RolePermissions
 */
export interface RolePermissions {
    /**
     * 
     * @type {UsersPermissions}
     * @memberof RolePermissions
     */
    'users'?: UsersPermissions | null;
    /**
     * 
     * @type {AdminsPermissions}
     * @memberof RolePermissions
     */
    'admins'?: AdminsPermissions | null;
    /**
     * 
     * @type {NodesPermissions}
     * @memberof RolePermissions
     */
    'nodes'?: NodesPermissions | null;
    /**
     * 
     * @type {CRUDPermissions}
     * @memberof RolePermissions
     */
    'groups'?: CRUDPermissions | null;
    /**
     * 
     * @type {HostsPermissions}
     * @memberof RolePermissions
     */
    'hosts'?: HostsPermissions | null;
    /**
     * 
     * @type {CRUDPermissions}
     * @memberof RolePermissions
     */
    'templates'?: CRUDPermissions | null;
    /**
     * 
     * @type {CRUDPermissions}
     * @memberof RolePermissions
     */
    'client_templates'?: CRUDPermissions | null;
    /**
     * 
     * @type {CRUDPermissions}
     * @memberof RolePermissions
     */
    'cores'?: CRUDPermissions | null;
    /**
     * 
     * @type {SettingsPermissions}
     * @memberof RolePermissions
     */
    'settings'?: SettingsPermissions | null;
    /**
     * 
     * @type {SystemPermissions}
     * @memberof RolePermissions
     */
    'system'?: SystemPermissions | null;
    /**
     * 
     * @type {HwidsPermissions}
     * @memberof RolePermissions
     */
    'hwids'?: HwidsPermissions | null;
    /**
     * 
     * @type {CRUDPermissions}
     * @memberof RolePermissions
     */
    'admin_roles'?: CRUDPermissions | null;
}

