/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RoleAccess
 */
export interface RoleAccess {
    /**
     * 
     * @type {boolean}
     * @memberof RoleAccess
     */
    'require_template'?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof RoleAccess
     */
    'allowed_template_ids'?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof RoleAccess
     */
    'allowed_group_ids'?: Array<number> | null;
}

