/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { General } from './general';
// May contain unused imports in some cases
// @ts-ignore
import type { HWIDSettings } from './hwidsettings';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationEnable } from './notification-enable';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationSettings } from './notification-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { Subscription } from './subscription';
// May contain unused imports in some cases
// @ts-ignore
import type { Telegram } from './telegram';
// May contain unused imports in some cases
// @ts-ignore
import type { Webhook } from './webhook';

/**
 * 
 * @export
 * @interface SettingsSchema
 */
export interface SettingsSchema {
    /**
     * 
     * @type {Telegram}
     * @memberof SettingsSchema
     */
    'telegram'?: Telegram | null;
    /**
     * 
     * @type {Webhook}
     * @memberof SettingsSchema
     */
    'webhook'?: Webhook | null;
    /**
     * 
     * @type {NotificationSettings}
     * @memberof SettingsSchema
     */
    'notification_settings'?: NotificationSettings | null;
    /**
     * 
     * @type {NotificationEnable}
     * @memberof SettingsSchema
     */
    'notification_enable'?: NotificationEnable | null;
    /**
     * 
     * @type {Subscription}
     * @memberof SettingsSchema
     */
    'subscription'?: Subscription | null;
    /**
     * 
     * @type {HWIDSettings}
     * @memberof SettingsSchema
     */
    'hwid'?: HWIDSettings | null;
    /**
     * 
     * @type {General}
     * @memberof SettingsSchema
     */
    'general'?: General | null;
}

