/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Read } from './read';
// May contain unused imports in some cases
// @ts-ignore
import type { ReadGeneral } from './read-general';
// May contain unused imports in some cases
// @ts-ignore
import type { Update } from './update';

/**
 * 
 * @export
 * @interface SettingsPermissions
 */
export interface SettingsPermissions {
    [key: string]: any;

    /**
     * 
     * @type {Read}
     * @memberof SettingsPermissions
     */
    'read'?: Read | null;
    /**
     * 
     * @type {ReadGeneral}
     * @memberof SettingsPermissions
     */
    'read_general'?: ReadGeneral | null;
    /**
     * 
     * @type {Update}
     * @memberof SettingsPermissions
     */
    'update'?: Update | null;
}

