/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskDomainSettings } from './final-mask-domain-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskMkcpLegacySettings } from './final-mask-mkcp-legacy-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskNoiseSettings } from './final-mask-noise-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskPasswordSettings } from './final-mask-password-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskRealmSettings } from './final-mask-realm-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskSalamanderSettings } from './final-mask-salamander-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskSudokuSettings } from './final-mask-sudoku-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskUdpHeaderCustomSettings } from './final-mask-udp-header-custom-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskXdnsSettings } from './final-mask-xdns-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskXicmpSettings } from './final-mask-xicmp-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { Reset } from './reset';
// May contain unused imports in some cases
// @ts-ignore
import type { XrayNoiseSettings } from './xray-noise-settings';

/**
 * @type Settings1
 * @export
 */
export type Settings1 = FinalMaskDomainSettings | FinalMaskMkcpLegacySettings | FinalMaskNoiseSettings | FinalMaskPasswordSettings | FinalMaskRealmSettings | FinalMaskSalamanderSettings | FinalMaskSudokuSettings | FinalMaskUdpHeaderCustomSettings | FinalMaskXdnsSettings | FinalMaskXicmpSettings | { [key: string]: any; };

