/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskFragmentSettings } from './final-mask-fragment-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskFragmentSettingsLengthsInner } from './final-mask-fragment-settings-lengths-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskSudokuSettings } from './final-mask-sudoku-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskTcpHeaderCustomSettings } from './final-mask-tcp-header-custom-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskXmcProfile } from './final-mask-xmc-profile';
// May contain unused imports in some cases
// @ts-ignore
import type { FinalMaskXmcSettings } from './final-mask-xmc-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { Maxsplit } from './maxsplit';
// May contain unused imports in some cases
// @ts-ignore
import type { XrayNoiseSettings } from './xray-noise-settings';

/**
 * @type Settings
 * @export
 */
export type Settings = FinalMaskFragmentSettings | FinalMaskSudokuSettings | FinalMaskTcpHeaderCustomSettings | FinalMaskXmcSettings | { [key: string]: any; };

