/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { General } from './general';
// May contain unused imports in some cases
// @ts-ignore
import type { HWIDSettings } from './hwidsettings';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationEnable } from './notification-enable';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationSettings } from './notification-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { Subscription } from './subscription';
// May contain unused imports in some cases
// @ts-ignore
import type { Telegram } from './telegram';
// May contain unused imports in some cases
// @ts-ignore
import type { Webhook } from './webhook';

export interface SettingsSchema {
    'telegram'?: Telegram | null;
    'webhook'?: Webhook | null;
    'notification_settings'?: NotificationSettings | null;
    'notification_enable'?: NotificationEnable | null;
    'subscription'?: Subscription | null;
    'hwid'?: HWIDSettings | null;
    'general'?: General | null;
}

