/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Application } from './application';
// May contain unused imports in some cases
// @ts-ignore
import type { CustomVariable } from './custom-variable';
// May contain unused imports in some cases
// @ts-ignore
import type { SubFormatEnable } from './sub-format-enable';
// May contain unused imports in some cases
// @ts-ignore
import type { SubRule } from './sub-rule';

export interface Subscription {
    'url_prefix'?: string;
    'update_interval'?: number;
    'support_url'?: string;
    'profile_title'?: string;
    'announce'?: string;
    'announce_url'?: string;
    'response_headers'?: { [key: string]: any; };
    'rules': Array<SubRule>;
    'manual_sub_request'?: SubFormatEnable;
    'applications'?: Array<Application>;
    'allow_browser_config'?: boolean;
    'disable_sub_template'?: boolean;
    'randomize_order'?: boolean;
    'custom_variables'?: Array<CustomVariable>;
}

