/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Application } from './application';
// May contain unused imports in some cases
// @ts-ignore
import type { SubFormatEnable } from './sub-format-enable';
// May contain unused imports in some cases
// @ts-ignore
import type { SubRule } from './sub-rule';

/**
 * 
 * @export
 * @interface Subscription
 */
export interface Subscription {
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    'url_prefix'?: string;
    /**
     * 
     * @type {number}
     * @memberof Subscription
     */
    'update_interval'?: number;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    'support_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    'profile_title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    'announce'?: string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    'announce_url'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Subscription
     */
    'response_headers'?: { [key: string]: any; };
    /**
     * 
     * @type {Array<SubRule>}
     * @memberof Subscription
     */
    'rules': Array<SubRule>;
    /**
     * 
     * @type {SubFormatEnable}
     * @memberof Subscription
     */
    'manual_sub_request'?: SubFormatEnable;
    /**
     * 
     * @type {Array<Application>}
     * @memberof Subscription
     */
    'applications'?: Array<Application>;
    /**
     * 
     * @type {boolean}
     * @memberof Subscription
     */
    'allow_browser_config'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Subscription
     */
    'disable_sub_template'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Subscription
     */
    'randomize_order'?: boolean;
}

