/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SystemStats {
    'total_user': number;
    'online_users': number;
    'active_users': number;
    'on_hold_users': number;
    'disabled_users': number;
    'expired_users': number;
    'limited_users': number;
    'incoming_bandwidth': number;
    'outgoing_bandwidth': number;
    'version': string;
    'uptime_seconds': number;
    'mem_total'?: number | null;
    'mem_used'?: number | null;
    'disk_total'?: number | null;
    'disk_used'?: number | null;
    'cpu_cores'?: number | null;
    'cpu_usage'?: number | null;
}

