/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SystemUsersStats {
    'total_user': number;
    'online_users': number;
    'active_users': number;
    'on_hold_users': number;
    'disabled_users': number;
    'expired_users': number;
    'limited_users': number;
    'incoming_bandwidth': number;
    'outgoing_bandwidth': number;
}

