/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SystemResourceStats
 */
export interface SystemResourceStats {
    /**
     * 
     * @type {string}
     * @memberof SystemResourceStats
     */
    'version': string;
    /**
     * 
     * @type {number}
     * @memberof SystemResourceStats
     */
    'uptime_seconds': number;
    /**
     * 
     * @type {number}
     * @memberof SystemResourceStats
     */
    'mem_total'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SystemResourceStats
     */
    'mem_used'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SystemResourceStats
     */
    'disk_total'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SystemResourceStats
     */
    'disk_used'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SystemResourceStats
     */
    'cpu_cores'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SystemResourceStats
     */
    'cpu_usage'?: number | null;
}

