/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SystemUsersStats
 */
export interface SystemUsersStats {
    /**
     * 
     * @type {number}
     * @memberof SystemUsersStats
     */
    'total_user': number;
    /**
     * 
     * @type {number}
     * @memberof SystemUsersStats
     */
    'online_users': number;
    /**
     * 
     * @type {number}
     * @memberof SystemUsersStats
     */
    'active_users': number;
    /**
     * 
     * @type {number}
     * @memberof SystemUsersStats
     */
    'on_hold_users': number;
    /**
     * 
     * @type {number}
     * @memberof SystemUsersStats
     */
    'disabled_users': number;
    /**
     * 
     * @type {number}
     * @memberof SystemUsersStats
     */
    'expired_users': number;
    /**
     * 
     * @type {number}
     * @memberof SystemUsersStats
     */
    'limited_users': number;
    /**
     * 
     * @type {number}
     * @memberof SystemUsersStats
     */
    'incoming_bandwidth': number;
    /**
     * 
     * @type {number}
     * @memberof SystemUsersStats
     */
    'outgoing_bandwidth': number;
}

