/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { RunMethod } from './run-method';

export interface Telegram {
    'enable'?: boolean;
    'token'?: string | null;
    'webhook_url'?: string | null;
    'webhook_secret'?: string | null;
    'proxy_url'?: string | null;
    'method'?: RunMethod;
    'mini_app_login'?: boolean;
    'mini_app_web_url'?: string | null;
    'for_admins_only'?: boolean;
}



