/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GRPCSettings } from './grpcsettings';
// May contain unused imports in some cases
// @ts-ignore
import type { KCPSettings } from './kcpsettings';
// May contain unused imports in some cases
// @ts-ignore
import type { TcpSettings } from './tcp-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { WebSocketSettings } from './web-socket-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { XHttpSettings } from './xhttp-settings';

export interface TransportSettings {
    'xhttp_settings'?: XHttpSettings | null;
    'grpc_settings'?: GRPCSettings | null;
    'kcp_settings'?: KCPSettings | null;
    'tcp_settings'?: TcpSettings | null;
    'websocket_settings'?: WebSocketSettings | null;
}

