/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { DataLimitResetStrategy } from './data-limit-reset-strategy';
// May contain unused imports in some cases
// @ts-ignore
import type { Expire } from './expire';
// May contain unused imports in some cases
// @ts-ignore
import type { NextPlanModel } from './next-plan-model';
// May contain unused imports in some cases
// @ts-ignore
import type { OnHoldTimeout } from './on-hold-timeout';
// May contain unused imports in some cases
// @ts-ignore
import type { ProxyTable } from './proxy-table';
// May contain unused imports in some cases
// @ts-ignore
import type { UserStatus } from './user-status';

export interface UserModify {
    'proxy_settings'?: ProxyTable | null;
    'expire'?: Expire | null;
    /**
     * data_limit can be 0 or greater
     */
    'data_limit'?: number | null;
    'data_limit_reset_strategy'?: DataLimitResetStrategy | null;
    'note'?: string | null;
    /**
     * on_hold_expire_duration can be 0 or greater in seconds
     */
    'on_hold_expire_duration'?: number | null;
    'on_hold_timeout'?: OnHoldTimeout | null;
    'group_ids'?: Array<number> | null;
    'auto_delete_in_days'?: number | null;
    'hwid_limit'?: number | null;
    'next_plan'?: NextPlanModel | null;
    'status'?: UserStatus | null;
}



