/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DataLimitResetStrategy } from './data-limit-reset-strategy';
// May contain unused imports in some cases
// @ts-ignore
import type { Expire } from './expire';
// May contain unused imports in some cases
// @ts-ignore
import type { NextPlanModel } from './next-plan-model';
// May contain unused imports in some cases
// @ts-ignore
import type { OnHoldTimeout } from './on-hold-timeout';
// May contain unused imports in some cases
// @ts-ignore
import type { ProxyTable } from './proxy-table';
// May contain unused imports in some cases
// @ts-ignore
import type { UserStatus } from './user-status';

/**
 * 
 * @export
 * @interface UserModify
 */
export interface UserModify {
    /**
     * 
     * @type {ProxyTable}
     * @memberof UserModify
     */
    'proxy_settings'?: ProxyTable | null;
    /**
     * 
     * @type {Expire}
     * @memberof UserModify
     */
    'expire'?: Expire | null;
    /**
     * 
     * @type {number}
     * @memberof UserModify
     */
    'data_limit'?: number | null;
    /**
     * 
     * @type {DataLimitResetStrategy}
     * @memberof UserModify
     */
    'data_limit_reset_strategy'?: DataLimitResetStrategy | null;
    /**
     * 
     * @type {string}
     * @memberof UserModify
     */
    'note'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserModify
     */
    'on_hold_expire_duration'?: number | null;
    /**
     * 
     * @type {OnHoldTimeout}
     * @memberof UserModify
     */
    'on_hold_timeout'?: OnHoldTimeout | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UserModify
     */
    'group_ids'?: Array<number> | null;
    /**
     * 
     * @type {number}
     * @memberof UserModify
     */
    'auto_delete_in_days'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UserModify
     */
    'hwid_limit'?: number | null;
    /**
     * 
     * @type {NextPlanModel}
     * @memberof UserModify
     */
    'next_plan'?: NextPlanModel | null;
    /**
     * 
     * @type {UserStatus}
     * @memberof UserModify
     */
    'status'?: UserStatus | null;
}



