/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ActivateNextPlan } from './activate-next-plan';
// May contain unused imports in some cases
// @ts-ignore
import type { Create } from './create';
// May contain unused imports in some cases
// @ts-ignore
import type { Delete } from './delete';
// May contain unused imports in some cases
// @ts-ignore
import type { Read } from './read';
// May contain unused imports in some cases
// @ts-ignore
import type { ReadSimple } from './read-simple';
// May contain unused imports in some cases
// @ts-ignore
import type { ResetUsage } from './reset-usage';
// May contain unused imports in some cases
// @ts-ignore
import type { RevokeSub } from './revoke-sub';
// May contain unused imports in some cases
// @ts-ignore
import type { SetOwner } from './set-owner';
// May contain unused imports in some cases
// @ts-ignore
import type { Update } from './update';

export interface UsersPermissions {
    'create'?: Create | null;
    'read'?: Read | null;
    'read_simple'?: ReadSimple | null;
    'update'?: Update | null;
    'delete'?: Delete | null;
    'reset_usage'?: ResetUsage | null;
    'revoke_sub'?: RevokeSub | null;
    'set_owner'?: SetOwner | null;
    'activate_next_plan'?: ActivateNextPlan | null;
}

