/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Lightweight user model with only id and username for performance.
 * @export
 * @interface UserSimple
 */
export interface UserSimple {
    /**
     * 
     * @type {number}
     * @memberof UserSimple
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UserSimple
     */
    'username': string;
}

