/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Period } from './period';
// May contain unused imports in some cases
// @ts-ignore
import type { UserCountMetric } from './user-count-metric';
// May contain unused imports in some cases
// @ts-ignore
import type { UserCountMetricStat } from './user-count-metric-stat';

export interface UserCountMetricStatsList {
    'period'?: Period | null;
    'start': string;
    'end': string;
    'metric': UserCountMetric;
    'count_during_period'?: number;
    'stats': { [key: string]: Array<UserCountMetricStat>; };
}



