/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserHWIDResponse {
    'id': number;
    'hwid': string;
    'device_os'?: string | null;
    'os_version'?: string | null;
    'device_model'?: string | null;
    'created_at': string;
    'last_used_at': string;
}

