/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserTemplateSimple } from './user-template-simple';

/**
 * Response model for lightweight user template list.
 * @export
 * @interface UserTemplatesSimpleResponse
 */
export interface UserTemplatesSimpleResponse {
    /**
     * 
     * @type {Array<UserTemplateSimple>}
     * @memberof UserTemplatesSimpleResponse
     */
    'templates': Array<UserTemplateSimple>;
    /**
     * 
     * @type {number}
     * @memberof UserTemplatesSimpleResponse
     */
    'total': number;
}

