/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 3.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserSimple } from './user-simple';

/**
 * Response model for lightweight user list.
 * @export
 * @interface UsersSimpleResponse
 */
export interface UsersSimpleResponse {
    /**
     * 
     * @type {Array<UserSimple>}
     * @memberof UsersSimpleResponse
     */
    'users': Array<UserSimple>;
    /**
     * 
     * @type {number}
     * @memberof UsersSimpleResponse
     */
    'total': number;
}

