/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ActivateNextPlan } from './activate-next-plan';
// May contain unused imports in some cases
// @ts-ignore
import type { Create } from './create';
// May contain unused imports in some cases
// @ts-ignore
import type { Delete } from './delete';
// May contain unused imports in some cases
// @ts-ignore
import type { Read } from './read';
// May contain unused imports in some cases
// @ts-ignore
import type { ReadSimple } from './read-simple';
// May contain unused imports in some cases
// @ts-ignore
import type { ResetUsage } from './reset-usage';
// May contain unused imports in some cases
// @ts-ignore
import type { RevokeSub } from './revoke-sub';
// May contain unused imports in some cases
// @ts-ignore
import type { SetOwner } from './set-owner';
// May contain unused imports in some cases
// @ts-ignore
import type { Update } from './update';

/**
 * 
 * @export
 * @interface UsersPermissions
 */
export interface UsersPermissions {
    [key: string]: any;

    /**
     * 
     * @type {Create}
     * @memberof UsersPermissions
     */
    'create'?: Create | null;
    /**
     * 
     * @type {Read}
     * @memberof UsersPermissions
     */
    'read'?: Read | null;
    /**
     * 
     * @type {ReadSimple}
     * @memberof UsersPermissions
     */
    'read_simple'?: ReadSimple | null;
    /**
     * 
     * @type {Update}
     * @memberof UsersPermissions
     */
    'update'?: Update | null;
    /**
     * 
     * @type {Delete}
     * @memberof UsersPermissions
     */
    'delete'?: Delete | null;
    /**
     * 
     * @type {ResetUsage}
     * @memberof UsersPermissions
     */
    'reset_usage'?: ResetUsage | null;
    /**
     * 
     * @type {RevokeSub}
     * @memberof UsersPermissions
     */
    'revoke_sub'?: RevokeSub | null;
    /**
     * 
     * @type {SetOwner}
     * @memberof UsersPermissions
     */
    'set_owner'?: SetOwner | null;
    /**
     * 
     * @type {ActivateNextPlan}
     * @memberof UsersPermissions
     */
    'activate_next_plan'?: ActivateNextPlan | null;
}

