/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Lightweight user template model with only id and name for performance.
 * @export
 * @interface UserTemplateSimple
 */
export interface UserTemplateSimple {
    /**
     * 
     * @type {number}
     * @memberof UserTemplateSimple
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UserTemplateSimple
     */
    'name'?: string | null;
}

