/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserNotificationEnable {
    'create'?: boolean;
    'modify'?: boolean;
    'delete'?: boolean;
    'status_change'?: boolean;
    'reset_data_usage'?: boolean;
    'data_reset_by_next'?: boolean;
    'subscription_revoked'?: boolean;
}

