/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Period } from './period';
// May contain unused imports in some cases
// @ts-ignore
import type { UserCountMetric } from './user-count-metric';
// May contain unused imports in some cases
// @ts-ignore
import type { UserCountMetricStat } from './user-count-metric-stat';

/**
 * 
 * @export
 * @interface UserCountMetricStatsList
 */
export interface UserCountMetricStatsList {
    /**
     * 
     * @type {Period}
     * @memberof UserCountMetricStatsList
     */
    'period'?: Period | null;
    /**
     * 
     * @type {string}
     * @memberof UserCountMetricStatsList
     */
    'start': string;
    /**
     * 
     * @type {string}
     * @memberof UserCountMetricStatsList
     */
    'end': string;
    /**
     * 
     * @type {UserCountMetric}
     * @memberof UserCountMetricStatsList
     */
    'metric': UserCountMetric;
    /**
     * 
     * @type {number}
     * @memberof UserCountMetricStatsList
     */
    'count_during_period'?: number;
    /**
     * 
     * @type {{ [key: string]: Array<UserCountMetricStat>; }}
     * @memberof UserCountMetricStatsList
     */
    'stats': { [key: string]: Array<UserCountMetricStat>; };
}



