/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { DataLimitResetStrategy } from './data-limit-reset-strategy';
// May contain unused imports in some cases
// @ts-ignore
import type { ExtraSettings } from './extra-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { UserStatusCreate } from './user-status-create';

export interface UserTemplateModify {
    'name'?: string | null;
    /**
     * data_limit can be 0 or greater
     */
    'data_limit'?: number | null;
    'hwid_limit'?: number | null;
    /**
     * expire_duration can be 0 or greater in seconds
     */
    'expire_duration'?: number | null;
    'username_prefix'?: string | null;
    'username_suffix'?: string | null;
    'group_ids'?: Array<number> | null;
    'extra_settings'?: ExtraSettings | null;
    'status'?: UserStatusCreate | null;
    'reset_usages'?: boolean | null;
    'on_hold_timeout'?: number | null;
    'data_limit_reset_strategy'?: DataLimitResetStrategy;
    'is_disabled'?: boolean | null;
}



