/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Period } from './period';
// May contain unused imports in some cases
// @ts-ignore
import type { UserSubscriptionUpdateChartSegment } from './user-subscription-update-chart-segment';
// May contain unused imports in some cases
// @ts-ignore
import type { UserSubscriptionUpdateChartStat } from './user-subscription-update-chart-stat';

export interface UserSubscriptionUpdateChart {
    'period'?: Period | null;
    'start': string;
    'end': string;
    'total': number;
    'segments'?: Array<UserSubscriptionUpdateChartSegment>;
    'stats'?: Array<UserSubscriptionUpdateChartStat>;
}



