/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { WebhookInfo } from './webhook-info';

export interface Webhook {
    'enable'?: boolean;
    'webhooks'?: Array<WebhookInfo>;
    'days_left'?: Array<number>;
    'usage_percent'?: Array<number>;
    'timeout': number;
    'recurrent': number;
    'proxy_url'?: string | null;
}

