/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WireGuardSettings
 */
export interface WireGuardSettings {
    /**
     * 
     * @type {string}
     * @memberof WireGuardSettings
     */
    'private_key'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WireGuardSettings
     */
    'public_key'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof WireGuardSettings
     */
    'peer_ips'?: Array<string>;
}

