/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WireGuardSubnetUsage {
    'subnet': string;
    'interface_tags': Array<string>;
    'capacity': number;
    'used': number;
    'free': number;
    'free_ips': Array<string>;
}

