/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 4.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WireGuardPeerIPsReallocateResponse
 */
export interface WireGuardPeerIPsReallocateResponse {
    /**
     * 
     * @type {number}
     * @memberof WireGuardPeerIPsReallocateResponse
     */
    'wireguard_inbound_tags': number;
    /**
     * 
     * @type {number}
     * @memberof WireGuardPeerIPsReallocateResponse
     */
    'candidates': number;
    /**
     * 
     * @type {number}
     * @memberof WireGuardPeerIPsReallocateResponse
     */
    'updated': number;
    /**
     * 
     * @type {boolean}
     * @memberof WireGuardPeerIPsReallocateResponse
     */
    'dry_run': boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof WireGuardPeerIPsReallocateResponse
     */
    'sample_usernames': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof WireGuardPeerIPsReallocateResponse
     */
    'affected_users': number;
}

