/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WorkerHealth
 */
export interface WorkerHealth {
    /**
     * 
     * @type {string}
     * @memberof WorkerHealth
     */
    'status': string;
    /**
     * 
     * @type {number}
     * @memberof WorkerHealth
     */
    'response_time_ms'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WorkerHealth
     */
    'error'?: string | null;
}

