/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { XHttpModes } from './xhttp-modes';
// May contain unused imports in some cases
// @ts-ignore
import type { XMuxSettings } from './xmux-settings';

/**
 * 
 * @export
 * @interface XHttpSettings
 */
export interface XHttpSettings {
    /**
     * 
     * @type {XHttpModes}
     * @memberof XHttpSettings
     */
    'mode'?: XHttpModes | null;
    /**
     * 
     * @type {boolean}
     * @memberof XHttpSettings
     */
    'no_grpc_header'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof XHttpSettings
     */
    'x_padding_bytes'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof XHttpSettings
     */
    'x_padding_obfs_mode'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof XHttpSettings
     */
    'x_padding_key'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XHttpSettings
     */
    'x_padding_header'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XHttpSettings
     */
    'x_padding_placement'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XHttpSettings
     */
    'x_padding_method'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XHttpSettings
     */
    'uplink_http_method'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XHttpSettings
     */
    'session_placement'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XHttpSettings
     */
    'session_key'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XHttpSettings
     */
    'seq_placement'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XHttpSettings
     */
    'seq_key'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XHttpSettings
     */
    'uplink_data_placement'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XHttpSettings
     */
    'uplink_data_key'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XHttpSettings
     */
    'uplink_chunk_size'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XHttpSettings
     */
    'sc_max_each_post_bytes'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XHttpSettings
     */
    'sc_min_posts_interval_ms'?: string | null;
    /**
     * 
     * @type {XMuxSettings}
     * @memberof XHttpSettings
     */
    'xmux'?: XMuxSettings | null;
    /**
     * 
     * @type {number}
     * @memberof XHttpSettings
     */
    'download_settings'?: number | null;
}



