/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { XHttpModes } from './xhttp-modes';
// May contain unused imports in some cases
// @ts-ignore
import type { XMuxSettings } from './xmux-settings';

export interface XHttpSettings {
    'mode'?: XHttpModes | null;
    'no_grpc_header'?: boolean | null;
    'x_padding_bytes'?: string | null;
    'x_padding_obfs_mode'?: boolean | null;
    'x_padding_key'?: string | null;
    'x_padding_header'?: string | null;
    'x_padding_placement'?: string | null;
    'x_padding_method'?: string | null;
    'uplink_http_method'?: string | null;
    'session_placement'?: string | null;
    'session_key'?: string | null;
    'session_id_table'?: string | null;
    'session_id_length'?: string | null;
    'seq_placement'?: string | null;
    'seq_key'?: string | null;
    'uplink_data_placement'?: string | null;
    'uplink_data_key'?: string | null;
    'uplink_chunk_size'?: string | null;
    'sc_max_each_post_bytes'?: string | null;
    'sc_min_posts_interval_ms'?: string | null;
    'xmux'?: XMuxSettings | null;
    'download_settings'?: number | null;
}



