/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface XMuxSettings {
    'maxConcurrency'?: string | null;
    'maxConnections'?: string | null;
    'cMaxReuseTimes'?: string | null;
    'hMaxReusableSecs'?: string | null;
    'hMaxRequestTimes'?: string | null;
    'hKeepAlivePeriod'?: number | null;
}

