/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface XMuxSettingsInput
 */
export interface XMuxSettingsInput {
    /**
     * 
     * @type {string}
     * @memberof XMuxSettingsInput
     */
    'max_concurrency'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XMuxSettingsInput
     */
    'max_connections'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XMuxSettingsInput
     */
    'c_max_reuse_times'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XMuxSettingsInput
     */
    'h_max_reusable_secs'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XMuxSettingsInput
     */
    'h_max_request_times'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof XMuxSettingsInput
     */
    'h_keep_alive_period'?: number | null;
}

