/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface XMuxSettings
 */
export interface XMuxSettings {
    /**
     * 
     * @type {string}
     * @memberof XMuxSettings
     */
    'maxConcurrency'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XMuxSettings
     */
    'maxConnections'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XMuxSettings
     */
    'cMaxReuseTimes'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XMuxSettings
     */
    'hMaxReusableSecs'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof XMuxSettings
     */
    'hMaxRequestTimes'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof XMuxSettings
     */
    'hKeepAlivePeriod'?: number | null;
}

