/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Delay } from './delay';
// May contain unused imports in some cases
// @ts-ignore
import type { Packet } from './packet';
// May contain unused imports in some cases
// @ts-ignore
import type { Rand } from './rand';

/**
 * 
 * @export
 * @interface XrayNoiseSettings
 */
export interface XrayNoiseSettings {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof XrayNoiseSettings
     */
    'type': string;
    /**
     * 
     * @type {Packet}
     * @memberof XrayNoiseSettings
     */
    'packet'?: Packet | null;
    /**
     * 
     * @type {Delay}
     * @memberof XrayNoiseSettings
     */
    'delay'?: Delay | null;
    /**
     * 
     * @type {string}
     * @memberof XrayNoiseSettings
     */
    'apply_to'?: string;
    /**
     * 
     * @type {Rand}
     * @memberof XrayNoiseSettings
     */
    'rand'?: Rand | null;
    /**
     * 
     * @type {string}
     * @memberof XrayNoiseSettings
     */
    'randRange'?: string | null;
}

