/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Delay } from './delay';
// May contain unused imports in some cases
// @ts-ignore
import type { Packet } from './packet';
// May contain unused imports in some cases
// @ts-ignore
import type { Rand } from './rand';

export interface XrayNoiseSettings {
    [key: string]: any;

    'type': string;
    'packet'?: Packet | null;
    'delay'?: Delay | null;
    'apply_to'?: string;
    'rand'?: Rand | null;
    'randRange'?: string | null;
}

