/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface XrayFragmentSettingsOutput
 */
export interface XrayFragmentSettingsOutput {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof XrayFragmentSettingsOutput
     */
    'packets': string;
    /**
     * 
     * @type {string}
     * @memberof XrayFragmentSettingsOutput
     */
    'length': string;
    /**
     * 
     * @type {string}
     * @memberof XrayFragmentSettingsOutput
     */
    'delay': string;
    /**
     * 
     * @type {string}
     * @memberof XrayFragmentSettingsOutput
     */
    'maxSplit'?: string | null;
}

