/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AdminRoleCreate } from '../models';
// @ts-ignore
import type { AdminRoleModify } from '../models';
// @ts-ignore
import type { AdminRoleResponse } from '../models';
// @ts-ignore
import type { AdminRolesResponse } from '../models';
// @ts-ignore
import type { AdminRolesSimpleResponse } from '../models';
// @ts-ignore
import type { Conflict } from '../models';
// @ts-ignore
import type { Forbidden } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { NotFound } from '../models';
// @ts-ignore
import type { Unauthorized } from '../models';
/**
 * AdminRolesApi - axios parameter creator
 * @export
 */
export const AdminRolesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a new role. Owner only.
         * @summary Create Role
         * @param {AdminRoleCreate} adminRoleCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRole: async (adminRoleCreate: AdminRoleCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'adminRoleCreate' is not null or undefined
            assertParamExists('createRole', 'adminRoleCreate', adminRoleCreate)
            const localVarPath = `/api/admin-role`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(adminRoleCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a role. Owner only. Built-in roles and in-use roles cannot be deleted.
         * @summary Delete Role
         * @param {number} roleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRole: async (roleId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roleId' is not null or undefined
            assertParamExists('deleteRole', 'roleId', roleId)
            const localVarPath = `/api/admin-role/{role_id}`
                .replace(`{${"role_id"}}`, encodeURIComponent(String(roleId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a role by ID.
         * @summary Get Role
         * @param {number} roleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRole: async (roleId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roleId' is not null or undefined
            assertParamExists('getRole', 'roleId', roleId)
            const localVarPath = `/api/admin-role/{role_id}`
                .replace(`{${"role_id"}}`, encodeURIComponent(String(roleId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List all roles.
         * @summary Get Roles
         * @param {string | null} [search] 
         * @param {number | null} [offset] 
         * @param {number | null} [limit] 
         * @param {string | null} [sort] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoles: async (search?: string | null, offset?: number | null, limit?: number | null, sort?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin-roles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List all roles as lightweight id/name/is_owner tuples.
         * @summary Get Roles Simple
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRolesSimple: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/admin-roles/simple`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Modify a role. Owner only. Owner role cannot be modified.
         * @summary Modify Role
         * @param {number} roleId 
         * @param {AdminRoleModify} adminRoleModify 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyRole: async (roleId: number, adminRoleModify: AdminRoleModify, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roleId' is not null or undefined
            assertParamExists('modifyRole', 'roleId', roleId)
            // verify required parameter 'adminRoleModify' is not null or undefined
            assertParamExists('modifyRole', 'adminRoleModify', adminRoleModify)
            const localVarPath = `/api/admin-role/{role_id}`
                .replace(`{${"role_id"}}`, encodeURIComponent(String(roleId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(adminRoleModify, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminRolesApi - functional programming interface
 * @export
 */
export const AdminRolesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminRolesApiAxiosParamCreator(configuration)
    return {
        /**
         * Create a new role. Owner only.
         * @summary Create Role
         * @param {AdminRoleCreate} adminRoleCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createRole(adminRoleCreate: AdminRoleCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminRoleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createRole(adminRoleCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminRolesApi.createRole']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete a role. Owner only. Built-in roles and in-use roles cannot be deleted.
         * @summary Delete Role
         * @param {number} roleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteRole(roleId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteRole(roleId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminRolesApi.deleteRole']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get a role by ID.
         * @summary Get Role
         * @param {number} roleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRole(roleId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminRoleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRole(roleId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminRolesApi.getRole']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List all roles.
         * @summary Get Roles
         * @param {string | null} [search] 
         * @param {number | null} [offset] 
         * @param {number | null} [limit] 
         * @param {string | null} [sort] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRoles(search?: string | null, offset?: number | null, limit?: number | null, sort?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminRolesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRoles(search, offset, limit, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminRolesApi.getRoles']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List all roles as lightweight id/name/is_owner tuples.
         * @summary Get Roles Simple
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRolesSimple(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminRolesSimpleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRolesSimple(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminRolesApi.getRolesSimple']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Modify a role. Owner only. Owner role cannot be modified.
         * @summary Modify Role
         * @param {number} roleId 
         * @param {AdminRoleModify} adminRoleModify 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modifyRole(roleId: number, adminRoleModify: AdminRoleModify, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminRoleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modifyRole(roleId, adminRoleModify, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminRolesApi.modifyRole']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminRolesApi - factory interface
 * @export
 */
export const AdminRolesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminRolesApiFp(configuration)
    return {
        /**
         * Create a new role. Owner only.
         * @summary Create Role
         * @param {AdminRoleCreate} adminRoleCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRole(adminRoleCreate: AdminRoleCreate, options?: RawAxiosRequestConfig): AxiosPromise<AdminRoleResponse> {
            return localVarFp.createRole(adminRoleCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a role. Owner only. Built-in roles and in-use roles cannot be deleted.
         * @summary Delete Role
         * @param {number} roleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRole(roleId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteRole(roleId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a role by ID.
         * @summary Get Role
         * @param {number} roleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRole(roleId: number, options?: RawAxiosRequestConfig): AxiosPromise<AdminRoleResponse> {
            return localVarFp.getRole(roleId, options).then((request) => request(axios, basePath));
        },
        /**
         * List all roles.
         * @summary Get Roles
         * @param {string | null} [search] 
         * @param {number | null} [offset] 
         * @param {number | null} [limit] 
         * @param {string | null} [sort] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoles(search?: string | null, offset?: number | null, limit?: number | null, sort?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<AdminRolesResponse> {
            return localVarFp.getRoles(search, offset, limit, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * List all roles as lightweight id/name/is_owner tuples.
         * @summary Get Roles Simple
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRolesSimple(options?: RawAxiosRequestConfig): AxiosPromise<AdminRolesSimpleResponse> {
            return localVarFp.getRolesSimple(options).then((request) => request(axios, basePath));
        },
        /**
         * Modify a role. Owner only. Owner role cannot be modified.
         * @summary Modify Role
         * @param {number} roleId 
         * @param {AdminRoleModify} adminRoleModify 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyRole(roleId: number, adminRoleModify: AdminRoleModify, options?: RawAxiosRequestConfig): AxiosPromise<AdminRoleResponse> {
            return localVarFp.modifyRole(roleId, adminRoleModify, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminRolesApi - object-oriented interface
 * @export
 * @class AdminRolesApi
 * @extends {BaseAPI}
 */
export class AdminRolesApi extends BaseAPI {
    /**
     * Create a new role. Owner only.
     * @summary Create Role
     * @param {AdminRoleCreate} adminRoleCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminRolesApi
     */
    public createRole(adminRoleCreate: AdminRoleCreate, options?: RawAxiosRequestConfig) {
        return AdminRolesApiFp(this.configuration).createRole(adminRoleCreate, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Delete a role. Owner only. Built-in roles and in-use roles cannot be deleted.
     * @summary Delete Role
     * @param {number} roleId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminRolesApi
     */
    public deleteRole(roleId: number, options?: RawAxiosRequestConfig) {
        return AdminRolesApiFp(this.configuration).deleteRole(roleId, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Get a role by ID.
     * @summary Get Role
     * @param {number} roleId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminRolesApi
     */
    public getRole(roleId: number, options?: RawAxiosRequestConfig) {
        return AdminRolesApiFp(this.configuration).getRole(roleId, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * List all roles.
     * @summary Get Roles
     * @param {string | null} [search] 
     * @param {number | null} [offset] 
     * @param {number | null} [limit] 
     * @param {string | null} [sort] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminRolesApi
     */
    public getRoles(search?: string | null, offset?: number | null, limit?: number | null, sort?: string | null, options?: RawAxiosRequestConfig) {
        return AdminRolesApiFp(this.configuration).getRoles(search, offset, limit, sort, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * List all roles as lightweight id/name/is_owner tuples.
     * @summary Get Roles Simple
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminRolesApi
     */
    public getRolesSimple(options?: RawAxiosRequestConfig) {
        return AdminRolesApiFp(this.configuration).getRolesSimple(options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Modify a role. Owner only. Owner role cannot be modified.
     * @summary Modify Role
     * @param {number} roleId 
     * @param {AdminRoleModify} adminRoleModify 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminRolesApi
     */
    public modifyRole(roleId: number, adminRoleModify: AdminRoleModify, options?: RawAxiosRequestConfig) {
        return AdminRolesApiFp(this.configuration).modifyRole(roleId, adminRoleModify, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }
}

