/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BulkGroup } from '../models';
// @ts-ignore
import type { BulkGroupSelection } from '../models';
// @ts-ignore
import type { BulkGroupsActionResponse } from '../models';
// @ts-ignore
import type { Forbidden } from '../models';
// @ts-ignore
import type { GroupCreate } from '../models';
// @ts-ignore
import type { GroupModify } from '../models';
// @ts-ignore
import type { GroupResponse } from '../models';
// @ts-ignore
import type { GroupsResponse } from '../models';
// @ts-ignore
import type { GroupsSimpleResponse } from '../models';
// @ts-ignore
import type { HTTPException } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { NotFound } from '../models';
// @ts-ignore
import type { RemoveGroupsResponse } from '../models';
// @ts-ignore
import type { Unauthorized } from '../models';
/**
 * GroupsApi - axios parameter creator
 * @export
 */
export const GroupsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Bulk assign groups to multiple users, users under specific admins, or all users.  - **group_ids**: List of group IDs to add (required) - **users**: Optional list of user IDs to assign the groups to - **admins**: Optional list of admin IDs — their users will be targeted  Notes: - If neither \'users\' nor \'admins\' are provided, groups will be added to *all users* - Existing user-group associations will be ignored (no duplication) - Returns list of affected users (those who received new group associations)
         * @summary Bulk add groups to users
         * @param {BulkGroup} bulkGroup 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkAddGroupsToUsers: async (bulkGroup: BulkGroup, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkGroup' is not null or undefined
            assertParamExists('bulkAddGroupsToUsers', 'bulkGroup', bulkGroup)
            const localVarPath = `/api/groups/bulk/add`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkGroup, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete selected groups by ID.
         * @summary Bulk Delete Groups
         * @param {BulkGroupSelection} bulkGroupSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkDeleteGroups: async (bulkGroupSelection: BulkGroupSelection, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkGroupSelection' is not null or undefined
            assertParamExists('bulkDeleteGroups', 'bulkGroupSelection', bulkGroupSelection)
            const localVarPath = `/api/groups/bulk/delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkGroupSelection, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Disable selected groups by ID.
         * @summary Bulk Disable Groups
         * @param {BulkGroupSelection} bulkGroupSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkDisableGroups: async (bulkGroupSelection: BulkGroupSelection, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkGroupSelection' is not null or undefined
            assertParamExists('bulkDisableGroups', 'bulkGroupSelection', bulkGroupSelection)
            const localVarPath = `/api/groups/bulk/disable`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkGroupSelection, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Enable selected groups by ID.
         * @summary Bulk Enable Groups
         * @param {BulkGroupSelection} bulkGroupSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkEnableGroups: async (bulkGroupSelection: BulkGroupSelection, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkGroupSelection' is not null or undefined
            assertParamExists('bulkEnableGroups', 'bulkGroupSelection', bulkGroupSelection)
            const localVarPath = `/api/groups/bulk/enable`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkGroupSelection, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Bulk remove groups from multiple users, users under specific admins, or all users.  - **group_ids**: List of group IDs to remove (required) - **users**: Optional list of user IDs to remove the groups from - **admins**: Optional list of admin IDs — their users will be targeted  Notes: - If neither \'users\' nor \'admins\' are provided, groups will be removed from *all users* - Only existing user-group associations will be removed - Returns list of affected users (those who had groups removed)
         * @summary Bulk remove groups from users
         * @param {BulkGroup} bulkGroup 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkRemoveUsersFromGroups: async (bulkGroup: BulkGroup, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkGroup' is not null or undefined
            assertParamExists('bulkRemoveUsersFromGroups', 'bulkGroup', bulkGroup)
            const localVarPath = `/api/groups/bulk/remove`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkGroup, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a new group in the system. Only authorized administrators can create groups.
         * @summary Create a new group
         * @param {GroupCreate} groupCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGroup: async (groupCreate: GroupCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupCreate' is not null or undefined
            assertParamExists('createGroup', 'groupCreate', groupCreate)
            const localVarPath = `/api/group`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(groupCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a paginated list of all groups in the system. Requires admin authentication.
         * @summary List all groups
         * @param {Array<number> | null} [ids] 
         * @param {number | null} [offset] 
         * @param {number | null} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllGroups: async (ids?: Array<number> | null, offset?: number | null, limit?: number | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/groups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            if (ids) {
                localVarQueryParameter['ids'] = ids;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves detailed information about a specific group by its ID.
         * @summary Get group details
         * @param {number} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGroup: async (groupId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('getGroup', 'groupId', groupId)
            const localVarPath = `/api/group/{group_id}`
                .replace(`{${"group_id"}}`, encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns only id and name for groups. Optimized for dropdowns and autocomplete.
         * @summary Get lightweight group list
         * @param {Array<number> | null} [ids] 
         * @param {number | null} [offset] 
         * @param {number | null} [limit] 
         * @param {string | null} [search] 
         * @param {string | null} [sort] 
         * @param {boolean} [all] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGroupsSimple: async (ids?: Array<number> | null, offset?: number | null, limit?: number | null, search?: string | null, sort?: string | null, all?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/groups/simple`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            if (ids) {
                localVarQueryParameter['ids'] = ids;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (all !== undefined) {
                localVarQueryParameter['all'] = all;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates an existing group\'s information. Only authorized administrators can modify groups.
         * @summary Modify group
         * @param {number} groupId 
         * @param {GroupModify} groupModify 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyGroup: async (groupId: number, groupModify: GroupModify, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('modifyGroup', 'groupId', groupId)
            // verify required parameter 'groupModify' is not null or undefined
            assertParamExists('modifyGroup', 'groupModify', groupModify)
            const localVarPath = `/api/group/{group_id}`
                .replace(`{${"group_id"}}`, encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(groupModify, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes a group from the system. Only authorized administrators can delete groups.
         * @summary Remove group
         * @param {number} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeGroup: async (groupId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            assertParamExists('removeGroup', 'groupId', groupId)
            const localVarPath = `/api/group/{group_id}`
                .replace(`{${"group_id"}}`, encodeURIComponent(String(groupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GroupsApi - functional programming interface
 * @export
 */
export const GroupsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GroupsApiAxiosParamCreator(configuration)
    return {
        /**
         * Bulk assign groups to multiple users, users under specific admins, or all users.  - **group_ids**: List of group IDs to add (required) - **users**: Optional list of user IDs to assign the groups to - **admins**: Optional list of admin IDs — their users will be targeted  Notes: - If neither \'users\' nor \'admins\' are provided, groups will be added to *all users* - Existing user-group associations will be ignored (no duplication) - Returns list of affected users (those who received new group associations)
         * @summary Bulk add groups to users
         * @param {BulkGroup} bulkGroup 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkAddGroupsToUsers(bulkGroup: BulkGroup, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkAddGroupsToUsers(bulkGroup, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.bulkAddGroupsToUsers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete selected groups by ID.
         * @summary Bulk Delete Groups
         * @param {BulkGroupSelection} bulkGroupSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkDeleteGroups(bulkGroupSelection: BulkGroupSelection, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RemoveGroupsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkDeleteGroups(bulkGroupSelection, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.bulkDeleteGroups']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Disable selected groups by ID.
         * @summary Bulk Disable Groups
         * @param {BulkGroupSelection} bulkGroupSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkDisableGroups(bulkGroupSelection: BulkGroupSelection, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkGroupsActionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkDisableGroups(bulkGroupSelection, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.bulkDisableGroups']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Enable selected groups by ID.
         * @summary Bulk Enable Groups
         * @param {BulkGroupSelection} bulkGroupSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkEnableGroups(bulkGroupSelection: BulkGroupSelection, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkGroupsActionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkEnableGroups(bulkGroupSelection, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.bulkEnableGroups']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Bulk remove groups from multiple users, users under specific admins, or all users.  - **group_ids**: List of group IDs to remove (required) - **users**: Optional list of user IDs to remove the groups from - **admins**: Optional list of admin IDs — their users will be targeted  Notes: - If neither \'users\' nor \'admins\' are provided, groups will be removed from *all users* - Only existing user-group associations will be removed - Returns list of affected users (those who had groups removed)
         * @summary Bulk remove groups from users
         * @param {BulkGroup} bulkGroup 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkRemoveUsersFromGroups(bulkGroup: BulkGroup, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkRemoveUsersFromGroups(bulkGroup, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.bulkRemoveUsersFromGroups']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Creates a new group in the system. Only authorized administrators can create groups.
         * @summary Create a new group
         * @param {GroupCreate} groupCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createGroup(groupCreate: GroupCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createGroup(groupCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.createGroup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves a paginated list of all groups in the system. Requires admin authentication.
         * @summary List all groups
         * @param {Array<number> | null} [ids] 
         * @param {number | null} [offset] 
         * @param {number | null} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllGroups(ids?: Array<number> | null, offset?: number | null, limit?: number | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllGroups(ids, offset, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.getAllGroups']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves detailed information about a specific group by its ID.
         * @summary Get group details
         * @param {number} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGroup(groupId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGroup(groupId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.getGroup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns only id and name for groups. Optimized for dropdowns and autocomplete.
         * @summary Get lightweight group list
         * @param {Array<number> | null} [ids] 
         * @param {number | null} [offset] 
         * @param {number | null} [limit] 
         * @param {string | null} [search] 
         * @param {string | null} [sort] 
         * @param {boolean} [all] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGroupsSimple(ids?: Array<number> | null, offset?: number | null, limit?: number | null, search?: string | null, sort?: string | null, all?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupsSimpleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getGroupsSimple(ids, offset, limit, search, sort, all, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.getGroupsSimple']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates an existing group\'s information. Only authorized administrators can modify groups.
         * @summary Modify group
         * @param {number} groupId 
         * @param {GroupModify} groupModify 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modifyGroup(groupId: number, groupModify: GroupModify, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GroupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modifyGroup(groupId, groupModify, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.modifyGroup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deletes a group from the system. Only authorized administrators can delete groups.
         * @summary Remove group
         * @param {number} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeGroup(groupId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeGroup(groupId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GroupsApi.removeGroup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GroupsApi - factory interface
 * @export
 */
export const GroupsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GroupsApiFp(configuration)
    return {
        /**
         * Bulk assign groups to multiple users, users under specific admins, or all users.  - **group_ids**: List of group IDs to add (required) - **users**: Optional list of user IDs to assign the groups to - **admins**: Optional list of admin IDs — their users will be targeted  Notes: - If neither \'users\' nor \'admins\' are provided, groups will be added to *all users* - Existing user-group associations will be ignored (no duplication) - Returns list of affected users (those who received new group associations)
         * @summary Bulk add groups to users
         * @param {BulkGroup} bulkGroup 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkAddGroupsToUsers(bulkGroup: BulkGroup, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.bulkAddGroupsToUsers(bulkGroup, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete selected groups by ID.
         * @summary Bulk Delete Groups
         * @param {BulkGroupSelection} bulkGroupSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkDeleteGroups(bulkGroupSelection: BulkGroupSelection, options?: RawAxiosRequestConfig): AxiosPromise<RemoveGroupsResponse> {
            return localVarFp.bulkDeleteGroups(bulkGroupSelection, options).then((request) => request(axios, basePath));
        },
        /**
         * Disable selected groups by ID.
         * @summary Bulk Disable Groups
         * @param {BulkGroupSelection} bulkGroupSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkDisableGroups(bulkGroupSelection: BulkGroupSelection, options?: RawAxiosRequestConfig): AxiosPromise<BulkGroupsActionResponse> {
            return localVarFp.bulkDisableGroups(bulkGroupSelection, options).then((request) => request(axios, basePath));
        },
        /**
         * Enable selected groups by ID.
         * @summary Bulk Enable Groups
         * @param {BulkGroupSelection} bulkGroupSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkEnableGroups(bulkGroupSelection: BulkGroupSelection, options?: RawAxiosRequestConfig): AxiosPromise<BulkGroupsActionResponse> {
            return localVarFp.bulkEnableGroups(bulkGroupSelection, options).then((request) => request(axios, basePath));
        },
        /**
         * Bulk remove groups from multiple users, users under specific admins, or all users.  - **group_ids**: List of group IDs to remove (required) - **users**: Optional list of user IDs to remove the groups from - **admins**: Optional list of admin IDs — their users will be targeted  Notes: - If neither \'users\' nor \'admins\' are provided, groups will be removed from *all users* - Only existing user-group associations will be removed - Returns list of affected users (those who had groups removed)
         * @summary Bulk remove groups from users
         * @param {BulkGroup} bulkGroup 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkRemoveUsersFromGroups(bulkGroup: BulkGroup, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.bulkRemoveUsersFromGroups(bulkGroup, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a new group in the system. Only authorized administrators can create groups.
         * @summary Create a new group
         * @param {GroupCreate} groupCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createGroup(groupCreate: GroupCreate, options?: RawAxiosRequestConfig): AxiosPromise<GroupResponse> {
            return localVarFp.createGroup(groupCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a paginated list of all groups in the system. Requires admin authentication.
         * @summary List all groups
         * @param {Array<number> | null} [ids] 
         * @param {number | null} [offset] 
         * @param {number | null} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllGroups(ids?: Array<number> | null, offset?: number | null, limit?: number | null, options?: RawAxiosRequestConfig): AxiosPromise<GroupsResponse> {
            return localVarFp.getAllGroups(ids, offset, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves detailed information about a specific group by its ID.
         * @summary Get group details
         * @param {number} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGroup(groupId: number, options?: RawAxiosRequestConfig): AxiosPromise<GroupResponse> {
            return localVarFp.getGroup(groupId, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns only id and name for groups. Optimized for dropdowns and autocomplete.
         * @summary Get lightweight group list
         * @param {Array<number> | null} [ids] 
         * @param {number | null} [offset] 
         * @param {number | null} [limit] 
         * @param {string | null} [search] 
         * @param {string | null} [sort] 
         * @param {boolean} [all] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGroupsSimple(ids?: Array<number> | null, offset?: number | null, limit?: number | null, search?: string | null, sort?: string | null, all?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<GroupsSimpleResponse> {
            return localVarFp.getGroupsSimple(ids, offset, limit, search, sort, all, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates an existing group\'s information. Only authorized administrators can modify groups.
         * @summary Modify group
         * @param {number} groupId 
         * @param {GroupModify} groupModify 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyGroup(groupId: number, groupModify: GroupModify, options?: RawAxiosRequestConfig): AxiosPromise<GroupResponse> {
            return localVarFp.modifyGroup(groupId, groupModify, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes a group from the system. Only authorized administrators can delete groups.
         * @summary Remove group
         * @param {number} groupId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeGroup(groupId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeGroup(groupId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GroupsApi - object-oriented interface
 * @export
 * @class GroupsApi
 * @extends {BaseAPI}
 */
export class GroupsApi extends BaseAPI {
    /**
     * Bulk assign groups to multiple users, users under specific admins, or all users.  - **group_ids**: List of group IDs to add (required) - **users**: Optional list of user IDs to assign the groups to - **admins**: Optional list of admin IDs — their users will be targeted  Notes: - If neither \'users\' nor \'admins\' are provided, groups will be added to *all users* - Existing user-group associations will be ignored (no duplication) - Returns list of affected users (those who received new group associations)
     * @summary Bulk add groups to users
     * @param {BulkGroup} bulkGroup 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApi
     */
    public bulkAddGroupsToUsers(bulkGroup: BulkGroup, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).bulkAddGroupsToUsers(bulkGroup, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Delete selected groups by ID.
     * @summary Bulk Delete Groups
     * @param {BulkGroupSelection} bulkGroupSelection 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApi
     */
    public bulkDeleteGroups(bulkGroupSelection: BulkGroupSelection, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).bulkDeleteGroups(bulkGroupSelection, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Disable selected groups by ID.
     * @summary Bulk Disable Groups
     * @param {BulkGroupSelection} bulkGroupSelection 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApi
     */
    public bulkDisableGroups(bulkGroupSelection: BulkGroupSelection, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).bulkDisableGroups(bulkGroupSelection, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Enable selected groups by ID.
     * @summary Bulk Enable Groups
     * @param {BulkGroupSelection} bulkGroupSelection 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApi
     */
    public bulkEnableGroups(bulkGroupSelection: BulkGroupSelection, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).bulkEnableGroups(bulkGroupSelection, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Bulk remove groups from multiple users, users under specific admins, or all users.  - **group_ids**: List of group IDs to remove (required) - **users**: Optional list of user IDs to remove the groups from - **admins**: Optional list of admin IDs — their users will be targeted  Notes: - If neither \'users\' nor \'admins\' are provided, groups will be removed from *all users* - Only existing user-group associations will be removed - Returns list of affected users (those who had groups removed)
     * @summary Bulk remove groups from users
     * @param {BulkGroup} bulkGroup 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApi
     */
    public bulkRemoveUsersFromGroups(bulkGroup: BulkGroup, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).bulkRemoveUsersFromGroups(bulkGroup, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Creates a new group in the system. Only authorized administrators can create groups.
     * @summary Create a new group
     * @param {GroupCreate} groupCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApi
     */
    public createGroup(groupCreate: GroupCreate, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).createGroup(groupCreate, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Retrieves a paginated list of all groups in the system. Requires admin authentication.
     * @summary List all groups
     * @param {Array<number> | null} [ids] 
     * @param {number | null} [offset] 
     * @param {number | null} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApi
     */
    public getAllGroups(ids?: Array<number> | null, offset?: number | null, limit?: number | null, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).getAllGroups(ids, offset, limit, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Retrieves detailed information about a specific group by its ID.
     * @summary Get group details
     * @param {number} groupId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApi
     */
    public getGroup(groupId: number, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).getGroup(groupId, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Returns only id and name for groups. Optimized for dropdowns and autocomplete.
     * @summary Get lightweight group list
     * @param {Array<number> | null} [ids] 
     * @param {number | null} [offset] 
     * @param {number | null} [limit] 
     * @param {string | null} [search] 
     * @param {string | null} [sort] 
     * @param {boolean} [all] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApi
     */
    public getGroupsSimple(ids?: Array<number> | null, offset?: number | null, limit?: number | null, search?: string | null, sort?: string | null, all?: boolean, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).getGroupsSimple(ids, offset, limit, search, sort, all, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Updates an existing group\'s information. Only authorized administrators can modify groups.
     * @summary Modify group
     * @param {number} groupId 
     * @param {GroupModify} groupModify 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApi
     */
    public modifyGroup(groupId: number, groupModify: GroupModify, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).modifyGroup(groupId, groupModify, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Deletes a group from the system. Only authorized administrators can delete groups.
     * @summary Remove group
     * @param {number} groupId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GroupsApi
     */
    public removeGroup(groupId: number, options?: RawAxiosRequestConfig) {
        return GroupsApiFp(this.configuration).removeGroup(groupId, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }
}

