/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseHost } from '../models';
// @ts-ignore
import type { BulkHostSelection } from '../models';
// @ts-ignore
import type { BulkHostsActionResponse } from '../models';
// @ts-ignore
import type { CreateHost } from '../models';
// @ts-ignore
import type { Forbidden } from '../models';
// @ts-ignore
import type { HTTPException } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { NotFound } from '../models';
// @ts-ignore
import type { RemoveHostsResponse } from '../models';
// @ts-ignore
import type { Unauthorized } from '../models';
/**
 * HostApi - axios parameter creator
 * @export
 */
export const HostApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Delete selected hosts by ID.
         * @summary Bulk Delete Hosts
         * @param {BulkHostSelection} bulkHostSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkDeleteHosts: async (bulkHostSelection: BulkHostSelection, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkHostSelection' is not null or undefined
            assertParamExists('bulkDeleteHosts', 'bulkHostSelection', bulkHostSelection)
            const localVarPath = `/api/hosts/bulk/delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkHostSelection, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Disable selected hosts by ID.
         * @summary Bulk Disable Hosts
         * @param {BulkHostSelection} bulkHostSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkDisableHosts: async (bulkHostSelection: BulkHostSelection, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkHostSelection' is not null or undefined
            assertParamExists('bulkDisableHosts', 'bulkHostSelection', bulkHostSelection)
            const localVarPath = `/api/hosts/bulk/disable`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkHostSelection, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Enable selected hosts by ID.
         * @summary Bulk Enable Hosts
         * @param {BulkHostSelection} bulkHostSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkEnableHosts: async (bulkHostSelection: BulkHostSelection, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkHostSelection' is not null or undefined
            assertParamExists('bulkEnableHosts', 'bulkHostSelection', bulkHostSelection)
            const localVarPath = `/api/hosts/bulk/enable`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkHostSelection, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * create a new host  **inbound_tag** must be available in one of the configured cores
         * @summary Create Host
         * @param {CreateHost} createHost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createHost: async (createHost: CreateHost, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createHost' is not null or undefined
            assertParamExists('createHost', 'createHost', createHost)
            const localVarPath = `/api/host/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createHost, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * get host by **id**
         * @summary Get Host
         * @param {number} hostId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHost: async (hostId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'hostId' is not null or undefined
            assertParamExists('getHost', 'hostId', hostId)
            const localVarPath = `/api/host/{host_id}`
                .replace(`{${"host_id"}}`, encodeURIComponent(String(hostId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get proxy hosts.
         * @summary Get Hosts
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHosts: async (offset?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/hosts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * modify host by **id**  **inbound_tag** must be available in one of the configured cores
         * @summary Modify Host
         * @param {number} hostId 
         * @param {CreateHost} createHost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyHost: async (hostId: number, createHost: CreateHost, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'hostId' is not null or undefined
            assertParamExists('modifyHost', 'hostId', hostId)
            // verify required parameter 'createHost' is not null or undefined
            assertParamExists('modifyHost', 'createHost', createHost)
            const localVarPath = `/api/host/{host_id}`
                .replace(`{${"host_id"}}`, encodeURIComponent(String(hostId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createHost, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Modify proxy hosts and update the configuration.
         * @summary Modify Hosts
         * @param {Array<CreateHost>} createHost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyHosts: async (createHost: Array<CreateHost>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createHost' is not null or undefined
            assertParamExists('modifyHosts', 'createHost', createHost)
            const localVarPath = `/api/hosts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createHost, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * remove host by **id**
         * @summary Remove Host
         * @param {number} hostId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeHost: async (hostId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'hostId' is not null or undefined
            assertParamExists('removeHost', 'hostId', hostId)
            const localVarPath = `/api/host/{host_id}`
                .replace(`{${"host_id"}}`, encodeURIComponent(String(hostId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HostApi - functional programming interface
 * @export
 */
export const HostApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HostApiAxiosParamCreator(configuration)
    return {
        /**
         * Delete selected hosts by ID.
         * @summary Bulk Delete Hosts
         * @param {BulkHostSelection} bulkHostSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkDeleteHosts(bulkHostSelection: BulkHostSelection, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RemoveHostsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkDeleteHosts(bulkHostSelection, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HostApi.bulkDeleteHosts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Disable selected hosts by ID.
         * @summary Bulk Disable Hosts
         * @param {BulkHostSelection} bulkHostSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkDisableHosts(bulkHostSelection: BulkHostSelection, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkHostsActionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkDisableHosts(bulkHostSelection, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HostApi.bulkDisableHosts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Enable selected hosts by ID.
         * @summary Bulk Enable Hosts
         * @param {BulkHostSelection} bulkHostSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkEnableHosts(bulkHostSelection: BulkHostSelection, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkHostsActionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkEnableHosts(bulkHostSelection, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HostApi.bulkEnableHosts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * create a new host  **inbound_tag** must be available in one of the configured cores
         * @summary Create Host
         * @param {CreateHost} createHost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createHost(createHost: CreateHost, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseHost>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createHost(createHost, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HostApi.createHost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * get host by **id**
         * @summary Get Host
         * @param {number} hostId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHost(hostId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseHost>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHost(hostId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HostApi.getHost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get proxy hosts.
         * @summary Get Hosts
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHosts(offset?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BaseHost>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHosts(offset, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HostApi.getHosts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * modify host by **id**  **inbound_tag** must be available in one of the configured cores
         * @summary Modify Host
         * @param {number} hostId 
         * @param {CreateHost} createHost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modifyHost(hostId: number, createHost: CreateHost, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseHost>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modifyHost(hostId, createHost, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HostApi.modifyHost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Modify proxy hosts and update the configuration.
         * @summary Modify Hosts
         * @param {Array<CreateHost>} createHost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modifyHosts(createHost: Array<CreateHost>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BaseHost>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modifyHosts(createHost, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HostApi.modifyHosts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * remove host by **id**
         * @summary Remove Host
         * @param {number} hostId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeHost(hostId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeHost(hostId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HostApi.removeHost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HostApi - factory interface
 * @export
 */
export const HostApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HostApiFp(configuration)
    return {
        /**
         * Delete selected hosts by ID.
         * @summary Bulk Delete Hosts
         * @param {BulkHostSelection} bulkHostSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkDeleteHosts(bulkHostSelection: BulkHostSelection, options?: RawAxiosRequestConfig): AxiosPromise<RemoveHostsResponse> {
            return localVarFp.bulkDeleteHosts(bulkHostSelection, options).then((request) => request(axios, basePath));
        },
        /**
         * Disable selected hosts by ID.
         * @summary Bulk Disable Hosts
         * @param {BulkHostSelection} bulkHostSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkDisableHosts(bulkHostSelection: BulkHostSelection, options?: RawAxiosRequestConfig): AxiosPromise<BulkHostsActionResponse> {
            return localVarFp.bulkDisableHosts(bulkHostSelection, options).then((request) => request(axios, basePath));
        },
        /**
         * Enable selected hosts by ID.
         * @summary Bulk Enable Hosts
         * @param {BulkHostSelection} bulkHostSelection 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkEnableHosts(bulkHostSelection: BulkHostSelection, options?: RawAxiosRequestConfig): AxiosPromise<BulkHostsActionResponse> {
            return localVarFp.bulkEnableHosts(bulkHostSelection, options).then((request) => request(axios, basePath));
        },
        /**
         * create a new host  **inbound_tag** must be available in one of the configured cores
         * @summary Create Host
         * @param {CreateHost} createHost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createHost(createHost: CreateHost, options?: RawAxiosRequestConfig): AxiosPromise<BaseHost> {
            return localVarFp.createHost(createHost, options).then((request) => request(axios, basePath));
        },
        /**
         * get host by **id**
         * @summary Get Host
         * @param {number} hostId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHost(hostId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseHost> {
            return localVarFp.getHost(hostId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get proxy hosts.
         * @summary Get Hosts
         * @param {number} [offset] 
         * @param {number} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHosts(offset?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<BaseHost>> {
            return localVarFp.getHosts(offset, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * modify host by **id**  **inbound_tag** must be available in one of the configured cores
         * @summary Modify Host
         * @param {number} hostId 
         * @param {CreateHost} createHost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyHost(hostId: number, createHost: CreateHost, options?: RawAxiosRequestConfig): AxiosPromise<BaseHost> {
            return localVarFp.modifyHost(hostId, createHost, options).then((request) => request(axios, basePath));
        },
        /**
         * Modify proxy hosts and update the configuration.
         * @summary Modify Hosts
         * @param {Array<CreateHost>} createHost 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyHosts(createHost: Array<CreateHost>, options?: RawAxiosRequestConfig): AxiosPromise<Array<BaseHost>> {
            return localVarFp.modifyHosts(createHost, options).then((request) => request(axios, basePath));
        },
        /**
         * remove host by **id**
         * @summary Remove Host
         * @param {number} hostId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeHost(hostId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeHost(hostId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HostApi - object-oriented interface
 * @export
 * @class HostApi
 * @extends {BaseAPI}
 */
export class HostApi extends BaseAPI {
    /**
     * Delete selected hosts by ID.
     * @summary Bulk Delete Hosts
     * @param {BulkHostSelection} bulkHostSelection 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HostApi
     */
    public bulkDeleteHosts(bulkHostSelection: BulkHostSelection, options?: RawAxiosRequestConfig) {
        return HostApiFp(this.configuration).bulkDeleteHosts(bulkHostSelection, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Disable selected hosts by ID.
     * @summary Bulk Disable Hosts
     * @param {BulkHostSelection} bulkHostSelection 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HostApi
     */
    public bulkDisableHosts(bulkHostSelection: BulkHostSelection, options?: RawAxiosRequestConfig) {
        return HostApiFp(this.configuration).bulkDisableHosts(bulkHostSelection, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Enable selected hosts by ID.
     * @summary Bulk Enable Hosts
     * @param {BulkHostSelection} bulkHostSelection 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HostApi
     */
    public bulkEnableHosts(bulkHostSelection: BulkHostSelection, options?: RawAxiosRequestConfig) {
        return HostApiFp(this.configuration).bulkEnableHosts(bulkHostSelection, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * create a new host  **inbound_tag** must be available in one of the configured cores
     * @summary Create Host
     * @param {CreateHost} createHost 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HostApi
     */
    public createHost(createHost: CreateHost, options?: RawAxiosRequestConfig) {
        return HostApiFp(this.configuration).createHost(createHost, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * get host by **id**
     * @summary Get Host
     * @param {number} hostId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HostApi
     */
    public getHost(hostId: number, options?: RawAxiosRequestConfig) {
        return HostApiFp(this.configuration).getHost(hostId, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Get proxy hosts.
     * @summary Get Hosts
     * @param {number} [offset] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HostApi
     */
    public getHosts(offset?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return HostApiFp(this.configuration).getHosts(offset, limit, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * modify host by **id**  **inbound_tag** must be available in one of the configured cores
     * @summary Modify Host
     * @param {number} hostId 
     * @param {CreateHost} createHost 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HostApi
     */
    public modifyHost(hostId: number, createHost: CreateHost, options?: RawAxiosRequestConfig) {
        return HostApiFp(this.configuration).modifyHost(hostId, createHost, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Modify proxy hosts and update the configuration.
     * @summary Modify Hosts
     * @param {Array<CreateHost>} createHost 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HostApi
     */
    public modifyHosts(createHost: Array<CreateHost>, options?: RawAxiosRequestConfig) {
        return HostApiFp(this.configuration).modifyHosts(createHost, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * remove host by **id**
     * @summary Remove Host
     * @param {number} hostId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HostApi
     */
    public removeHost(hostId: number, options?: RawAxiosRequestConfig) {
        return HostApiFp(this.configuration).removeHost(hostId, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }
}

