/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AdminDetails } from '../models';
// @ts-ignore
import type { Conflict } from '../models';
// @ts-ignore
import type { HTTPException } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { NotFound } from '../models';
// @ts-ignore
import type { OwnerCreateRequest } from '../models';
// @ts-ignore
import type { OwnerResetRequest } from '../models';
// @ts-ignore
import type { OwnerUpgradeRequest } from '../models';
/**
 * SetupApi - axios parameter creator
 * @export
 */
export const SetupApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create the owner admin using a one-time temp key.
         * @summary Create Owner
         * @param {OwnerCreateRequest} ownerCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOwner: async (ownerCreateRequest: OwnerCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ownerCreateRequest' is not null or undefined
            assertParamExists('createOwner', 'ownerCreateRequest', ownerCreateRequest)
            const localVarPath = `/api/setup/owner`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ownerCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete the owner admin using a one-time temp key.
         * @summary Delete Owner
         * @param {string} key One-time temp key for deleting the owner admin
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOwner: async (key: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'key' is not null or undefined
            assertParamExists('deleteOwner', 'key', key)
            const localVarPath = `/api/setup/owner`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (key !== undefined) {
                localVarQueryParameter['key'] = key;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Reset the owner admin\'s password using a one-time temp key.
         * @summary Reset Owner Password
         * @param {OwnerResetRequest} ownerResetRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetOwnerPassword: async (ownerResetRequest: OwnerResetRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ownerResetRequest' is not null or undefined
            assertParamExists('resetOwnerPassword', 'ownerResetRequest', ownerResetRequest)
            const localVarPath = `/api/setup/owner`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ownerResetRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Upgrade an existing admin to owner using a one-time temp key.
         * @summary Upgrade Owner
         * @param {OwnerUpgradeRequest} ownerUpgradeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upgradeOwner: async (ownerUpgradeRequest: OwnerUpgradeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ownerUpgradeRequest' is not null or undefined
            assertParamExists('upgradeOwner', 'ownerUpgradeRequest', ownerUpgradeRequest)
            const localVarPath = `/api/setup/owner/upgrade`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ownerUpgradeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SetupApi - functional programming interface
 * @export
 */
export const SetupApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SetupApiAxiosParamCreator(configuration)
    return {
        /**
         * Create the owner admin using a one-time temp key.
         * @summary Create Owner
         * @param {OwnerCreateRequest} ownerCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOwner(ownerCreateRequest: OwnerCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminDetails>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOwner(ownerCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SetupApi.createOwner']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete the owner admin using a one-time temp key.
         * @summary Delete Owner
         * @param {string} key One-time temp key for deleting the owner admin
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteOwner(key: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteOwner(key, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SetupApi.deleteOwner']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Reset the owner admin\'s password using a one-time temp key.
         * @summary Reset Owner Password
         * @param {OwnerResetRequest} ownerResetRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resetOwnerPassword(ownerResetRequest: OwnerResetRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminDetails>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resetOwnerPassword(ownerResetRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SetupApi.resetOwnerPassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Upgrade an existing admin to owner using a one-time temp key.
         * @summary Upgrade Owner
         * @param {OwnerUpgradeRequest} ownerUpgradeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async upgradeOwner(ownerUpgradeRequest: OwnerUpgradeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdminDetails>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.upgradeOwner(ownerUpgradeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SetupApi.upgradeOwner']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SetupApi - factory interface
 * @export
 */
export const SetupApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SetupApiFp(configuration)
    return {
        /**
         * Create the owner admin using a one-time temp key.
         * @summary Create Owner
         * @param {OwnerCreateRequest} ownerCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOwner(ownerCreateRequest: OwnerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdminDetails> {
            return localVarFp.createOwner(ownerCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete the owner admin using a one-time temp key.
         * @summary Delete Owner
         * @param {string} key One-time temp key for deleting the owner admin
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOwner(key: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteOwner(key, options).then((request) => request(axios, basePath));
        },
        /**
         * Reset the owner admin\'s password using a one-time temp key.
         * @summary Reset Owner Password
         * @param {OwnerResetRequest} ownerResetRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetOwnerPassword(ownerResetRequest: OwnerResetRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdminDetails> {
            return localVarFp.resetOwnerPassword(ownerResetRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Upgrade an existing admin to owner using a one-time temp key.
         * @summary Upgrade Owner
         * @param {OwnerUpgradeRequest} ownerUpgradeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upgradeOwner(ownerUpgradeRequest: OwnerUpgradeRequest, options?: RawAxiosRequestConfig): AxiosPromise<AdminDetails> {
            return localVarFp.upgradeOwner(ownerUpgradeRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SetupApi - object-oriented interface
 * @export
 * @class SetupApi
 * @extends {BaseAPI}
 */
export class SetupApi extends BaseAPI {
    /**
     * Create the owner admin using a one-time temp key.
     * @summary Create Owner
     * @param {OwnerCreateRequest} ownerCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SetupApi
     */
    public createOwner(ownerCreateRequest: OwnerCreateRequest, options?: RawAxiosRequestConfig) {
        return SetupApiFp(this.configuration).createOwner(ownerCreateRequest, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Delete the owner admin using a one-time temp key.
     * @summary Delete Owner
     * @param {string} key One-time temp key for deleting the owner admin
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SetupApi
     */
    public deleteOwner(key: string, options?: RawAxiosRequestConfig) {
        return SetupApiFp(this.configuration).deleteOwner(key, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Reset the owner admin\'s password using a one-time temp key.
     * @summary Reset Owner Password
     * @param {OwnerResetRequest} ownerResetRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SetupApi
     */
    public resetOwnerPassword(ownerResetRequest: OwnerResetRequest, options?: RawAxiosRequestConfig) {
        return SetupApiFp(this.configuration).resetOwnerPassword(ownerResetRequest, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Upgrade an existing admin to owner using a one-time temp key.
     * @summary Upgrade Owner
     * @param {OwnerUpgradeRequest} ownerUpgradeRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SetupApi
     */
    public upgradeOwner(ownerUpgradeRequest: OwnerUpgradeRequest, options?: RawAxiosRequestConfig) {
        return SetupApiFp(this.configuration).upgradeOwner(ownerUpgradeRequest, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }
}

