/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Application } from '../models';
// @ts-ignore
import type { ConfigFormat } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { Period } from '../models';
// @ts-ignore
import type { SubscriptionUserResponse } from '../models';
// @ts-ignore
import type { UserUsageStatsList } from '../models';
/**
 * SubscriptionApi - axios parameter creator
 * @export
 */
export const SubscriptionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Fetches the usage statistics for the user within a specified date range.
         * @summary Get Sub User Usage
         * @param {string} token 
         * @param {Period} [period] 
         * @param {string | null} [start] 
         * @param {string | null} [end] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubUserUsage: async (token: string, period?: Period, start?: string | null, end?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('getSubUserUsage', 'token', token)
            const localVarPath = `/sub/{token}/usage`
                .replace(`{${"token"}}`, encodeURIComponent(String(token)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (period !== undefined) {
                localVarQueryParameter['period'] = period;
            }

            if (start !== undefined) {
                localVarQueryParameter['start'] = (start as any instanceof Date) ?
                    (start as any).toISOString() :
                    start;
            }

            if (end !== undefined) {
                localVarQueryParameter['end'] = (end as any instanceof Date) ?
                    (end as any).toISOString() :
                    end;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Provides a subscription link based on the user agent (Clash, V2Ray, etc.).
         * @summary User Subscription
         * @param {string} token 
         * @param {string} [userAgent] 
         * @param {string | null} [xHWID] 
         * @param {string | null} [xDeviceOS] 
         * @param {string | null} [xVerOS] 
         * @param {string | null} [xDeviceModel] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userSubscription: async (token: string, userAgent?: string, xHWID?: string | null, xDeviceOS?: string | null, xVerOS?: string | null, xDeviceModel?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('userSubscription', 'token', token)
            const localVarPath = `/sub/{token}/`
                .replace(`{${"token"}}`, encodeURIComponent(String(token)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (userAgent != null) {
                localVarHeaderParameter['user-agent'] = String(userAgent);
            }
            if (xHWID != null) {
                localVarHeaderParameter['X-HWID'] = String(xHWID);
            }
            if (xDeviceOS != null) {
                localVarHeaderParameter['X-Device-OS'] = String(xDeviceOS);
            }
            if (xVerOS != null) {
                localVarHeaderParameter['X-Ver-OS'] = String(xVerOS);
            }
            if (xDeviceModel != null) {
                localVarHeaderParameter['X-Device-Model'] = String(xDeviceModel);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get applications available for user\'s subscription.
         * @summary User Subscription Apps
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userSubscriptionApps: async (token: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('userSubscriptionApps', 'token', token)
            const localVarPath = `/sub/{token}/apps`
                .replace(`{${"token"}}`, encodeURIComponent(String(token)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Provides subscription headers without response body.
         * @summary User Subscription Headers
         * @param {string} token 
         * @param {string} [userAgent] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userSubscriptionHeaders: async (token: string, userAgent?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('userSubscriptionHeaders', 'token', token)
            const localVarPath = `/sub/{token}/`
                .replace(`{${"token"}}`, encodeURIComponent(String(token)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'HEAD', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (userAgent != null) {
                localVarHeaderParameter['user-agent'] = String(userAgent);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves detailed information about the user\'s subscription.
         * @summary User Subscription Info
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userSubscriptionInfo: async (token: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('userSubscriptionInfo', 'token', token)
            const localVarPath = `/sub/{token}/info`
                .replace(`{${"token"}}`, encodeURIComponent(String(token)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary User Subscription Raw
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userSubscriptionRaw: async (token: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('userSubscriptionRaw', 'token', token)
            const localVarPath = `/sub/{token}/raw`
                .replace(`{${"token"}}`, encodeURIComponent(String(token)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Provides a subscription link based on the specified client type (e.g., Clash, V2Ray).
         * @summary User Subscription With Client Type
         * @param {string} token 
         * @param {ConfigFormat} clientType 
         * @param {string | null} [xHWID] 
         * @param {string | null} [xDeviceOS] 
         * @param {string | null} [xVerOS] 
         * @param {string | null} [xDeviceModel] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userSubscriptionWithClientType: async (token: string, clientType: ConfigFormat, xHWID?: string | null, xDeviceOS?: string | null, xVerOS?: string | null, xDeviceModel?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('userSubscriptionWithClientType', 'token', token)
            // verify required parameter 'clientType' is not null or undefined
            assertParamExists('userSubscriptionWithClientType', 'clientType', clientType)
            const localVarPath = `/sub/{token}/{client_type}`
                .replace(`{${"token"}}`, encodeURIComponent(String(token)))
                .replace(`{${"client_type"}}`, encodeURIComponent(String(clientType)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xHWID != null) {
                localVarHeaderParameter['X-HWID'] = String(xHWID);
            }
            if (xDeviceOS != null) {
                localVarHeaderParameter['X-Device-OS'] = String(xDeviceOS);
            }
            if (xVerOS != null) {
                localVarHeaderParameter['X-Ver-OS'] = String(xVerOS);
            }
            if (xDeviceModel != null) {
                localVarHeaderParameter['X-Device-Model'] = String(xDeviceModel);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SubscriptionApi - functional programming interface
 * @export
 */
export const SubscriptionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SubscriptionApiAxiosParamCreator(configuration)
    return {
        /**
         * Fetches the usage statistics for the user within a specified date range.
         * @summary Get Sub User Usage
         * @param {string} token 
         * @param {Period} [period] 
         * @param {string | null} [start] 
         * @param {string | null} [end] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSubUserUsage(token: string, period?: Period, start?: string | null, end?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserUsageStatsList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSubUserUsage(token, period, start, end, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionApi.getSubUserUsage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Provides a subscription link based on the user agent (Clash, V2Ray, etc.).
         * @summary User Subscription
         * @param {string} token 
         * @param {string} [userAgent] 
         * @param {string | null} [xHWID] 
         * @param {string | null} [xDeviceOS] 
         * @param {string | null} [xVerOS] 
         * @param {string | null} [xDeviceModel] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userSubscription(token: string, userAgent?: string, xHWID?: string | null, xDeviceOS?: string | null, xVerOS?: string | null, xDeviceModel?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userSubscription(token, userAgent, xHWID, xDeviceOS, xVerOS, xDeviceModel, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionApi.userSubscription']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get applications available for user\'s subscription.
         * @summary User Subscription Apps
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userSubscriptionApps(token: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Application>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userSubscriptionApps(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionApi.userSubscriptionApps']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Provides subscription headers without response body.
         * @summary User Subscription Headers
         * @param {string} token 
         * @param {string} [userAgent] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userSubscriptionHeaders(token: string, userAgent?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userSubscriptionHeaders(token, userAgent, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionApi.userSubscriptionHeaders']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves detailed information about the user\'s subscription.
         * @summary User Subscription Info
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userSubscriptionInfo(token: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscriptionUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userSubscriptionInfo(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionApi.userSubscriptionInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary User Subscription Raw
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userSubscriptionRaw(token: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userSubscriptionRaw(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionApi.userSubscriptionRaw']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Provides a subscription link based on the specified client type (e.g., Clash, V2Ray).
         * @summary User Subscription With Client Type
         * @param {string} token 
         * @param {ConfigFormat} clientType 
         * @param {string | null} [xHWID] 
         * @param {string | null} [xDeviceOS] 
         * @param {string | null} [xVerOS] 
         * @param {string | null} [xDeviceModel] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userSubscriptionWithClientType(token: string, clientType: ConfigFormat, xHWID?: string | null, xDeviceOS?: string | null, xVerOS?: string | null, xDeviceModel?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userSubscriptionWithClientType(token, clientType, xHWID, xDeviceOS, xVerOS, xDeviceModel, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SubscriptionApi.userSubscriptionWithClientType']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SubscriptionApi - factory interface
 * @export
 */
export const SubscriptionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SubscriptionApiFp(configuration)
    return {
        /**
         * Fetches the usage statistics for the user within a specified date range.
         * @summary Get Sub User Usage
         * @param {string} token 
         * @param {Period} [period] 
         * @param {string | null} [start] 
         * @param {string | null} [end] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSubUserUsage(token: string, period?: Period, start?: string | null, end?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<UserUsageStatsList> {
            return localVarFp.getSubUserUsage(token, period, start, end, options).then((request) => request(axios, basePath));
        },
        /**
         * Provides a subscription link based on the user agent (Clash, V2Ray, etc.).
         * @summary User Subscription
         * @param {string} token 
         * @param {string} [userAgent] 
         * @param {string | null} [xHWID] 
         * @param {string | null} [xDeviceOS] 
         * @param {string | null} [xVerOS] 
         * @param {string | null} [xDeviceModel] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userSubscription(token: string, userAgent?: string, xHWID?: string | null, xDeviceOS?: string | null, xVerOS?: string | null, xDeviceModel?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.userSubscription(token, userAgent, xHWID, xDeviceOS, xVerOS, xDeviceModel, options).then((request) => request(axios, basePath));
        },
        /**
         * Get applications available for user\'s subscription.
         * @summary User Subscription Apps
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userSubscriptionApps(token: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<Application>> {
            return localVarFp.userSubscriptionApps(token, options).then((request) => request(axios, basePath));
        },
        /**
         * Provides subscription headers without response body.
         * @summary User Subscription Headers
         * @param {string} token 
         * @param {string} [userAgent] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userSubscriptionHeaders(token: string, userAgent?: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.userSubscriptionHeaders(token, userAgent, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves detailed information about the user\'s subscription.
         * @summary User Subscription Info
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userSubscriptionInfo(token: string, options?: RawAxiosRequestConfig): AxiosPromise<SubscriptionUserResponse> {
            return localVarFp.userSubscriptionInfo(token, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary User Subscription Raw
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userSubscriptionRaw(token: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.userSubscriptionRaw(token, options).then((request) => request(axios, basePath));
        },
        /**
         * Provides a subscription link based on the specified client type (e.g., Clash, V2Ray).
         * @summary User Subscription With Client Type
         * @param {string} token 
         * @param {ConfigFormat} clientType 
         * @param {string | null} [xHWID] 
         * @param {string | null} [xDeviceOS] 
         * @param {string | null} [xVerOS] 
         * @param {string | null} [xDeviceModel] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userSubscriptionWithClientType(token: string, clientType: ConfigFormat, xHWID?: string | null, xDeviceOS?: string | null, xVerOS?: string | null, xDeviceModel?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.userSubscriptionWithClientType(token, clientType, xHWID, xDeviceOS, xVerOS, xDeviceModel, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SubscriptionApi - object-oriented interface
 * @export
 * @class SubscriptionApi
 * @extends {BaseAPI}
 */
export class SubscriptionApi extends BaseAPI {
    /**
     * Fetches the usage statistics for the user within a specified date range.
     * @summary Get Sub User Usage
     * @param {string} token 
     * @param {Period} [period] 
     * @param {string | null} [start] 
     * @param {string | null} [end] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionApi
     */
    public getSubUserUsage(token: string, period?: Period, start?: string | null, end?: string | null, options?: RawAxiosRequestConfig) {
        return SubscriptionApiFp(this.configuration).getSubUserUsage(token, period, start, end, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Provides a subscription link based on the user agent (Clash, V2Ray, etc.).
     * @summary User Subscription
     * @param {string} token 
     * @param {string} [userAgent] 
     * @param {string | null} [xHWID] 
     * @param {string | null} [xDeviceOS] 
     * @param {string | null} [xVerOS] 
     * @param {string | null} [xDeviceModel] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionApi
     */
    public userSubscription(token: string, userAgent?: string, xHWID?: string | null, xDeviceOS?: string | null, xVerOS?: string | null, xDeviceModel?: string | null, options?: RawAxiosRequestConfig) {
        return SubscriptionApiFp(this.configuration).userSubscription(token, userAgent, xHWID, xDeviceOS, xVerOS, xDeviceModel, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Get applications available for user\'s subscription.
     * @summary User Subscription Apps
     * @param {string} token 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionApi
     */
    public userSubscriptionApps(token: string, options?: RawAxiosRequestConfig) {
        return SubscriptionApiFp(this.configuration).userSubscriptionApps(token, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Provides subscription headers without response body.
     * @summary User Subscription Headers
     * @param {string} token 
     * @param {string} [userAgent] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionApi
     */
    public userSubscriptionHeaders(token: string, userAgent?: string, options?: RawAxiosRequestConfig) {
        return SubscriptionApiFp(this.configuration).userSubscriptionHeaders(token, userAgent, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Retrieves detailed information about the user\'s subscription.
     * @summary User Subscription Info
     * @param {string} token 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionApi
     */
    public userSubscriptionInfo(token: string, options?: RawAxiosRequestConfig) {
        return SubscriptionApiFp(this.configuration).userSubscriptionInfo(token, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * 
     * @summary User Subscription Raw
     * @param {string} token 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionApi
     */
    public userSubscriptionRaw(token: string, options?: RawAxiosRequestConfig) {
        return SubscriptionApiFp(this.configuration).userSubscriptionRaw(token, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Provides a subscription link based on the specified client type (e.g., Clash, V2Ray).
     * @summary User Subscription With Client Type
     * @param {string} token 
     * @param {ConfigFormat} clientType 
     * @param {string | null} [xHWID] 
     * @param {string | null} [xDeviceOS] 
     * @param {string | null} [xVerOS] 
     * @param {string | null} [xDeviceModel] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubscriptionApi
     */
    public userSubscriptionWithClientType(token: string, clientType: ConfigFormat, xHWID?: string | null, xDeviceOS?: string | null, xVerOS?: string | null, xDeviceModel?: string | null, options?: RawAxiosRequestConfig) {
        return SubscriptionApiFp(this.configuration).userSubscriptionWithClientType(token, clientType, xHWID, xDeviceOS, xVerOS, xDeviceModel, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }
}

