/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 3.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { InboundSummary } from '../models';
// @ts-ignore
import type { SystemStats } from '../models';
// @ts-ignore
import type { Unauthorized } from '../models';
// @ts-ignore
import type { WorkersHealth } from '../models';
/**
 * SystemApi - axios parameter creator
 * @export
 */
export const SystemApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve lightweight inbound metadata for dashboard forms.
         * @summary Get Inbound Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInboundDetails: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/inbounds/details`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve inbound configurations grouped by protocol.
         * @summary Get Inbounds
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInbounds: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/inbounds`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetch system stats including memory, CPU, disk, and user metrics.
         * @summary Get System Stats
         * @param {string | null} [adminUsername] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSystemStats: async (adminUsername?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/system`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)

            if (adminUsername !== undefined) {
                localVarQueryParameter['admin_username'] = adminUsername;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Workers Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWorkersHealth: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/workers/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SystemApi - functional programming interface
 * @export
 */
export const SystemApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SystemApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve lightweight inbound metadata for dashboard forms.
         * @summary Get Inbound Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInboundDetails(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<InboundSummary>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInboundDetails(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemApi.getInboundDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve inbound configurations grouped by protocol.
         * @summary Get Inbounds
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInbounds(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<string | null>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInbounds(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemApi.getInbounds']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fetch system stats including memory, CPU, disk, and user metrics.
         * @summary Get System Stats
         * @param {string | null} [adminUsername] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSystemStats(adminUsername?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SystemStats>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSystemStats(adminUsername, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemApi.getSystemStats']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Workers Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWorkersHealth(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WorkersHealth>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWorkersHealth(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemApi.getWorkersHealth']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SystemApi - factory interface
 * @export
 */
export const SystemApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SystemApiFp(configuration)
    return {
        /**
         * Retrieve lightweight inbound metadata for dashboard forms.
         * @summary Get Inbound Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInboundDetails(options?: RawAxiosRequestConfig): AxiosPromise<Array<InboundSummary>> {
            return localVarFp.getInboundDetails(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve inbound configurations grouped by protocol.
         * @summary Get Inbounds
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInbounds(options?: RawAxiosRequestConfig): AxiosPromise<Array<string | null>> {
            return localVarFp.getInbounds(options).then((request) => request(axios, basePath));
        },
        /**
         * Fetch system stats including memory, CPU, disk, and user metrics.
         * @summary Get System Stats
         * @param {string | null} [adminUsername] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSystemStats(adminUsername?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<SystemStats> {
            return localVarFp.getSystemStats(adminUsername, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Workers Health
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWorkersHealth(options?: RawAxiosRequestConfig): AxiosPromise<WorkersHealth> {
            return localVarFp.getWorkersHealth(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SystemApi - object-oriented interface
 * @export
 * @class SystemApi
 * @extends {BaseAPI}
 */
export class SystemApi extends BaseAPI {
    /**
     * Retrieve lightweight inbound metadata for dashboard forms.
     * @summary Get Inbound Details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemApi
     */
    public getInboundDetails(options?: RawAxiosRequestConfig) {
        return SystemApiFp(this.configuration).getInboundDetails(options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Retrieve inbound configurations grouped by protocol.
     * @summary Get Inbounds
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemApi
     */
    public getInbounds(options?: RawAxiosRequestConfig) {
        return SystemApiFp(this.configuration).getInbounds(options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Fetch system stats including memory, CPU, disk, and user metrics.
     * @summary Get System Stats
     * @param {string | null} [adminUsername] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemApi
     */
    public getSystemStats(adminUsername?: string | null, options?: RawAxiosRequestConfig) {
        return SystemApiFp(this.configuration).getSystemStats(adminUsername, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * 
     * @summary Get Workers Health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemApi
     */
    public getWorkersHealth(options?: RawAxiosRequestConfig) {
        return SystemApiFp(this.configuration).getWorkersHealth(options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }
}

