/* tslint:disable */
/* eslint-disable */
/**
 * PasarGuardAPI
 * Unified GUI Censorship Resistant Solution
 *
 * The version of the OpenAPI document: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Forbidden } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { NotFound } from '../models';
// @ts-ignore
import type { Unauthorized } from '../models';
// @ts-ignore
import type { UserHWIDListResponse } from '../models';
/**
 * UserHWIDApi - axios parameter creator
 * @export
 */
export const UserHWIDApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Delete a specific hardware ID from user
         * @summary Delete User Hwid
         * @param {number} userId 
         * @param {string} hwid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUserHwid: async (userId: number, hwid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('deleteUserHwid', 'userId', userId)
            // verify required parameter 'hwid' is not null or undefined
            assertParamExists('deleteUserHwid', 'hwid', hwid)
            const localVarPath = `/api/user/{user_id}/hwids/{hwid}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)))
                .replace(`{${"hwid"}}`, encodeURIComponent(String(hwid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get user\'s registered hardware IDs
         * @summary Get User Hwids
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserHwids: async (userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserHwids', 'userId', userId)
            const localVarPath = `/api/user/{user_id}/hwids`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete all hardware IDs for user
         * @summary Reset User Hwids
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetUserHwids: async (userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('resetUserHwids', 'userId', userId)
            const localVarPath = `/api/user/{user_id}/hwids/reset`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2PasswordBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2PasswordBearer", [], configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserHWIDApi - functional programming interface
 * @export
 */
export const UserHWIDApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserHWIDApiAxiosParamCreator(configuration)
    return {
        /**
         * Delete a specific hardware ID from user
         * @summary Delete User Hwid
         * @param {number} userId 
         * @param {string} hwid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteUserHwid(userId: number, hwid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUserHwid(userId, hwid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserHWIDApi.deleteUserHwid']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get user\'s registered hardware IDs
         * @summary Get User Hwids
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserHwids(userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserHWIDListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserHwids(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserHWIDApi.getUserHwids']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete all hardware IDs for user
         * @summary Reset User Hwids
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resetUserHwids(userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resetUserHwids(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserHWIDApi.resetUserHwids']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserHWIDApi - factory interface
 * @export
 */
export const UserHWIDApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserHWIDApiFp(configuration)
    return {
        /**
         * Delete a specific hardware ID from user
         * @summary Delete User Hwid
         * @param {number} userId 
         * @param {string} hwid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUserHwid(userId: number, hwid: string, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.deleteUserHwid(userId, hwid, options).then((request) => request(axios, basePath));
        },
        /**
         * Get user\'s registered hardware IDs
         * @summary Get User Hwids
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserHwids(userId: number, options?: RawAxiosRequestConfig): AxiosPromise<UserHWIDListResponse> {
            return localVarFp.getUserHwids(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete all hardware IDs for user
         * @summary Reset User Hwids
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetUserHwids(userId: number, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.resetUserHwids(userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserHWIDApi - object-oriented interface
 * @export
 * @class UserHWIDApi
 * @extends {BaseAPI}
 */
export class UserHWIDApi extends BaseAPI {
    /**
     * Delete a specific hardware ID from user
     * @summary Delete User Hwid
     * @param {number} userId 
     * @param {string} hwid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserHWIDApi
     */
    public deleteUserHwid(userId: number, hwid: string, options?: RawAxiosRequestConfig) {
        return UserHWIDApiFp(this.configuration).deleteUserHwid(userId, hwid, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Get user\'s registered hardware IDs
     * @summary Get User Hwids
     * @param {number} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserHWIDApi
     */
    public getUserHwids(userId: number, options?: RawAxiosRequestConfig) {
        return UserHWIDApiFp(this.configuration).getUserHwids(userId, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }

    /**
     * Delete all hardware IDs for user
     * @summary Reset User Hwids
     * @param {number} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserHWIDApi
     */
    public resetUserHwids(userId: number, options?: RawAxiosRequestConfig) {
        return UserHWIDApiFp(this.configuration).resetUserHwids(userId, options).then((request) => request(this.axios, this.basePath)).then(({data}) => data);
    }
}

